import type { AnalyticsAvailability, AnalyticsSeries, TimeSeriesPoint } from "@/types";

type Bucket = "day" | "week" | "month";
const dateKey = (date: Date, bucket: Bucket): string => { if (bucket === "month") return `${date.getUTCFullYear()}-${String(date.getUTCMonth() + 1).padStart(2, "0")}`; if (bucket === "week") { const monday = new Date(Date.UTC(date.getUTCFullYear(), date.getUTCMonth(), date.getUTCDate() - ((date.getUTCDay() + 6) % 7))); return monday.toISOString().slice(0, 10); } return date.toISOString().slice(0, 10); };

export function normalizeSeries(points: readonly TimeSeriesPoint[], id: string, label: string): AnalyticsSeries { const deduped = new Map<string, TimeSeriesPoint>(); points.filter(point => Number.isFinite(point.value) && !Number.isNaN(Date.parse(point.timestamp))).forEach(point => deduped.set(point.timestamp, point)); return { id, label, points: Array.from(deduped.values()).sort((a, b) => Date.parse(a.timestamp) - Date.parse(b.timestamp)), availability: deduped.size ? "available" : "insufficient-data" }; }
export function aggregateSeries(points: readonly TimeSeriesPoint[], id: string, label: string, bucket: Bucket): AnalyticsSeries { const grouped = new Map<string, number>(); points.forEach(point => { const key = dateKey(new Date(point.timestamp), bucket); grouped.set(key, (grouped.get(key) ?? 0) + point.value); }); return normalizeSeries(Array.from(grouped.entries()).map(([timestamp, value]) => ({ timestamp: bucket === "month" ? `${timestamp}-01T00:00:00.000Z` : `${timestamp}T00:00:00.000Z`, value })), id, label); }
export function filterSeries(points: readonly TimeSeriesPoint[], from?: string, to?: string): TimeSeriesPoint[] { const start = from ? Date.parse(from) : -Infinity; const end = to ? Date.parse(to) : Infinity; return points.filter(point => { const time = Date.parse(point.timestamp); return time >= start && time <= end; }).sort((a, b) => Date.parse(a.timestamp) - Date.parse(b.timestamp)); }
export const seriesAvailability = (points: readonly TimeSeriesPoint[]): AnalyticsAvailability => points.length ? "available" : "insufficient-data";
