import { useMemo } from 'react';
import { Link } from 'react-router-dom';
import { Activity, ArrowRight, BarChart3, CalendarDays, CheckCircle2, Code2, Database, Plus, RefreshCw, Shield, Sparkles, Target } from 'lucide-react';
import { useProfileSnapshots, useTrackedProfiles } from '@/hooks/use-profiles';
import { allActivity, formatNumber, formatRelativeDate, numericMetrics, platformLabel, platformTone, snapshotDelta } from '@/lib/analytics/dashboard-data';
import type { ProfileSnapshot, TrackedProfile } from '@/lib/integrations/registry';
import { Card, CardContent } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { TimeRangeChart } from '@/components/analytics/TimeRangeChart';

const groups = [
  { id: 'development', query: 'development', title: 'Development', description: 'Code, repositories, contributions and developer activity.', icon: Code2, tone: 'blue', platforms: ['github', 'stackoverflow'] },
  { id: 'dsa', query: 'dsa', title: 'DSA / CP', description: 'Problems, contests, ratings and coding practice.', icon: BarChart3, tone: 'orange', platforms: ['codeforces', 'leetcode', 'codewars'] },
  { id: 'security', query: 'security', title: 'Cybersecurity', description: 'Labs, CTFs and security practice from connected sources.', icon: Shield, tone: 'emerald', platforms: ['portswigger', 'hacker101', 'tryhackme'] },
  { id: 'learning', query: 'learning', title: 'Learning', description: 'Learning-oriented progress and activity.', icon: Sparkles, tone: 'violet', platforms: ['leetcode', 'codewars'] },
  { id: 'projects', query: 'development', title: 'Projects', description: 'Project and repository activity from development sources.', icon: Target, tone: 'cyan', platforms: ['github'] },
] as const;
const toneClasses: Record<string, string> = { blue: 'border-blue-500/25 bg-blue-500/[0.06] text-blue-600 dark:text-blue-400', orange: 'border-orange-500/25 bg-orange-500/[0.06] text-orange-600 dark:text-orange-400', emerald: 'border-emerald-500/25 bg-emerald-500/[0.06] text-emerald-600 dark:text-emerald-400', violet: 'border-violet-500/25 bg-violet-500/[0.06] text-violet-600 dark:text-violet-400', cyan: 'border-cyan-500/25 bg-cyan-500/[0.06] text-cyan-600 dark:text-cyan-400' };
function categoryProfiles(profiles: TrackedProfile[], ids: readonly string[]) { return profiles.filter((profile) => ids.includes(profile.platform)); }
function categoryActivity(profiles: TrackedProfile[], ids: readonly string[]) { const map = new Map<string, number>(); for (const profile of categoryProfiles(profiles, ids)) for (const point of profile.data?.activity ?? []) if (point.date) map.set(point.date, (map.get(point.date) ?? 0) + Math.max(0, Number(point.count) || 0)); return Array.from(map, ([date, count]) => ({ date, count })).sort((a, b) => a.date.localeCompare(b.date)); }
function CategoryCard({ group, profiles }: { group: (typeof groups)[number]; profiles: TrackedProfile[] }) { const sourceProfiles = categoryProfiles(profiles, group.platforms); const activity = categoryActivity(profiles, group.platforms); const total = activity.reduce((sum, point) => sum + point.count, 0); const metrics = sourceProfiles.reduce((sum, profile) => sum + numericMetrics(profile).length, 0); const highlights = sourceProfiles.flatMap((profile) => numericMetrics(profile).slice(0, 2).map((metric) => `${metric.label}: ${formatNumber(metric.value)}`)).slice(0, 3); const Icon = group.icon; return <Link to={`/dashboard/integrations?category=${group.query}`} className="group block h-full"><Card className="h-full overflow-hidden bg-card/80 transition-all duration-300 hover:-translate-y-1 hover:border-primary/30 hover:shadow-xl"><CardContent className="p-5 sm:p-6"><div className="flex items-start justify-between gap-3"><div className={`flex h-11 w-11 items-center justify-center rounded-xl border ${toneClasses[group.tone]}`}><Icon className="h-5 w-5"/></div><Badge variant="outline" className={sourceProfiles.length ? 'border-emerald-500/30 text-emerald-600 dark:text-emerald-400' : ''}>{sourceProfiles.length ? `${sourceProfiles.length} connected` : 'Connect'}</Badge></div><p className="mt-5 text-xs font-semibold uppercase tracking-wider text-muted-foreground">{group.title}</p><h3 className="mt-1 text-2xl font-bold">{sourceProfiles.length ? formatNumber(total) : '0'}</h3><p className="mt-1 text-xs text-muted-foreground">{sourceProfiles.length ? 'returned activity' : 'connected sources'}</p><p className="mt-3 min-h-10 text-xs leading-5 text-muted-foreground">{group.description}</p><div className="mt-4 border-t border-border pt-4">{highlights.length ? highlights.map((item) => <p key={item} className="truncate text-[11px] text-muted-foreground">{item}</p>) : <p className="text-[11px] text-muted-foreground">Connect a supported source to populate this area.</p>}</div><div className="mt-4 flex items-center justify-between text-[11px] text-muted-foreground"><span>{metrics} numeric metrics</span><span className="font-medium text-primary">Open <ArrowRight className="ml-1 inline h-3 w-3"/></span></div></CardContent></Card></Link>; }
function ProfileStatCard({ profile, snapshots }: { profile: TrackedProfile; snapshots: ProfileSnapshot[] }) { const metrics = numericMetrics(profile).slice(0, 3); const main = metrics[0]; const delta = main ? snapshotDelta(snapshots, profile.id, main.key) : null; const tone = platformTone(profile.platform); return <Link to={`/dashboard/profile/${profile.id}`}><Card className="group h-full overflow-hidden bg-card/80 transition hover:-translate-y-1 hover:shadow-lg"><CardContent className="p-5"><div className="flex items-center justify-between gap-2"><div className={`flex h-10 w-10 items-center justify-center rounded-xl ${tone.bg} ${tone.text}`}><span className="text-sm font-black">{platformLabel(profile.platform).slice(0,1)}</span></div><Badge variant="outline">{platformLabel(profile.platform)}</Badge></div><p className="mt-4 truncate text-xs text-muted-foreground">{profile.displayName || profile.handle}</p><p className="truncate text-sm font-semibold">@{profile.handle}</p>{main ? <><p className="mt-4 text-3xl font-black">{formatNumber(main.value)}</p><p className="mt-1 text-xs text-muted-foreground">{main.label}</p></> : <p className="mt-4 text-sm text-muted-foreground">Public profile data</p>}<div className="mt-4 grid grid-cols-2 gap-2 border-t border-border pt-4">{metrics.slice(1).map((metric) => <div key={metric.key}><p className="text-sm font-bold">{formatNumber(metric.value)}</p><p className="truncate text-[10px] text-muted-foreground">{metric.label}</p></div>)}{delta && <div className="text-right"><p className={`text-sm font-bold ${delta.delta >= 0 ? 'text-emerald-500' : 'text-rose-500'}`}>{delta.delta >= 0 ? '+' : ''}{formatNumber(delta.delta)}</p><p className="text-[10px] text-muted-foreground">since first snapshot</p></div>}{profile.lastSyncedAt && !delta && <div className="text-right"><p className="text-sm font-medium">{formatRelativeDate(profile.lastSyncedAt)}</p><p className="text-[10px] text-muted-foreground">last synced</p></div>}</div></CardContent></Card></Link>; }
export function OverviewView() { const { data: profiles = [], isLoading, refetch } = useTrackedProfiles(); const { data: snapshots = [] } = useProfileSnapshots(); const activity = useMemo(() => allActivity(profiles), [profiles]); const total = activity.reduce((sum, point) => sum + point.count, 0); const metrics = profiles.reduce((sum, profile) => sum + numericMetrics(profile).length, 0); if (isLoading) return <div className="p-6"><div className="mx-auto max-w-7xl animate-pulse space-y-6"><div className="h-24 rounded-3xl bg-muted"/><div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">{[1,2,3,4,5].map((i) => <div key={i} className="h-64 rounded-3xl bg-muted"/>)}</div></div></div>;
return <div className="relative min-h-full overflow-hidden"><div className="pointer-events-none absolute -left-40 top-0 h-96 w-96 rounded-full bg-violet-500/[0.07] blur-3xl"/><div className="relative mx-auto max-w-7xl space-y-7 p-5 sm:p-6 lg:p-8"><header className="flex flex-col justify-between gap-4 sm:flex-row"><div><div className="mb-3 flex flex-wrap gap-2"><Badge variant="outline" className="border-violet-500/30 bg-violet-500/10 text-violet-700 dark:text-violet-300"><Sparkles className="mr-1.5 h-3 w-3"/>Personal Intelligence</Badge><Badge variant="outline">{profiles.length} connected</Badge></div><h1 className="text-3xl font-black tracking-tight sm:text-4xl">Your intelligence dashboard</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-muted-foreground">A real-time view of your development, DSA, security and learning signals.</p></div><div className="flex items-center gap-2 rounded-xl border border-border bg-card/70 px-3 py-2 text-xs text-muted-foreground"><CalendarDays className="h-3.5 w-3.5"/>{new Date().toLocaleDateString()}</div></header>
<Card className="border-emerald-500/20 bg-emerald-500/[0.03]"><CardContent className="p-5 sm:p-6"><div className="flex flex-col justify-between gap-4 lg:flex-row lg:items-center"><div className="flex items-start gap-3"><CheckCircle2 className="mt-0.5 h-5 w-5 shrink-0 text-emerald-500"/><div><p className="font-semibold">Real connected data</p><p className="mt-1 text-xs text-muted-foreground">{profiles.length} source{profiles.length === 1 ? '' : 's'} · {metrics} numeric metrics · {formatNumber(total)} returned activity count. Nothing is fabricated.</p></div></div><div className="flex gap-2"><Link to="/dashboard/integrations"><Button className="gap-2"><Plus className="h-4 w-4"/>Manage connections</Button></Link><Button variant="outline" size="sm" onClick={() => refetch()} className="gap-2"><RefreshCw className="h-3.5 w-3.5"/>Refresh</Button></div></div></CardContent></Card>
<section><div className="mb-4"><p className="text-xs font-semibold uppercase tracking-wider text-muted-foreground">Your areas</p><h2 className="mt-1 text-xl font-bold">Every category opens directly into its filtered integrations.</h2></div><div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">{groups.map((group) => <CategoryCard key={group.id} group={group} profiles={profiles}/>)}</div></section>
{profiles.length > 0 && <><section><div className="mb-4 flex items-end justify-between"><div><p className="text-xs font-semibold uppercase tracking-wider text-muted-foreground">Connected sources</p><h2 className="mt-1 text-xl font-bold">Platform snapshots</h2></div><Link to="/dashboard/profiles" className="text-xs font-medium text-primary">View profiles <ArrowRight className="ml-1 inline h-3 w-3"/></Link></div><div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">{profiles.map((profile) => <ProfileStatCard key={profile.id} profile={profile} snapshots={snapshots}/>)}</div></section><TimeRangeChart points={activity} title="Overall activity" subtitle="All connected sources normalized by day. The same 7-day, 30-day, 1-year and all-time controls are used everywhere."/></>}
{!profiles.length && <Card className="border-dashed"><CardContent className="p-12 text-center"><Database className="mx-auto h-10 w-10 text-muted-foreground/40"/><h2 className="mt-3 text-lg font-bold">Your dashboard is waiting for its first source</h2><p className="mx-auto mt-1 max-w-lg text-sm text-muted-foreground">Connect a platform and APIVue will populate this page with real returned data.</p><Link to="/dashboard/integrations"><Button className="mt-4">Connect a platform <ArrowRight className="ml-2 h-4 w-4"/></Button></Link></CardContent></Card>}</div></div>; }
