type SecurityProvider = 'tryhackme' | 'hackthebox';
type Metric = { key: string; label: string; value: number | string | null; format?: string };
export type SecurityProfile = { platform: SecurityProvider; handle: string; displayName: string; avatarUrl: string | null; profileUrl: string; bio: string | null; location: string | null; joinedAt: string | null; metrics: Metric[]; breakdowns: Array<{ key: string; label: string; unit?: string; items: Array<{ label: string; value: number }> }>; ratingHistory: Array<{ date: string; value: number }>; activity: Array<{ date: string; count: number }>; highlights: Array<{ title: string; url?: string; subtitle?: string }>; fetchedAt: string; dataSource?: string; dataNotice?: string };
async function json(url: string): Promise<any> { const res = await fetch(url, { headers: { Accept: 'application/json', 'User-Agent': 'APIVue/1.0' } }); if (!res.ok) throw new Error(`${new URL(url).hostname} responded ${res.status}`); return res.json(); }
export async function getConnectedSecurityProfile(provider: SecurityProvider, handle: string): Promise<SecurityProfile> {
  if (provider === 'tryhackme') {
    const clean = handle.trim().replace(/^@/, '');
    if (!/^[A-Za-z0-9_.-]{1,80}$/.test(clean)) throw new Error('Invalid TryHackMe username.');
    const payload = await json(`https://tryhackme.com/api/v2/public-profile?username=${encodeURIComponent(clean)}`); const user = payload?.data;
    if (payload?.status !== 'success' || !user?.username) throw new Error(`TryHackMe public profile "${clean}" was not found or is unavailable.`);
    return { platform: 'tryhackme', handle: user.username, displayName: user.username, avatarUrl: user.avatar ?? null, profileUrl: `https://tryhackme.com/p/${encodeURIComponent(user.username)}`, bio: user.about ?? null, location: user.country ?? null, joinedAt: user.dateSignUp ?? null,
      metrics: [{ key: 'points', label: 'Points', value: Number(user.totalPoints ?? 0), format: 'number' }, { key: 'rank', label: 'Rank', value: Number(user.rank ?? 0), format: 'number' }, { key: 'rooms_completed', label: 'Rooms completed', value: Number(user.completedRoomsNumber ?? 0), format: 'number' }, { key: 'badges', label: 'Badges', value: Number(user.badgesNumber ?? 0), format: 'number' }, { key: 'level', label: 'Level', value: Number(user.level ?? 0), format: 'number' }, { key: 'top_percentage', label: 'Top percentage', value: Number(user.topPercentage ?? 0), format: 'percent' }, { key: 'streak', label: 'Streak', value: Number(user.streak ?? 0), format: 'number' }],
      breakdowns: [], ratingHistory: [], activity: [], highlights: [{ title: `${user.leagueTier ?? 'Unknown'} league`, subtitle: user.isInTopTenPercent ? 'Top 10% indicator published by TryHackMe' : 'Platform profile data' }], fetchedAt: new Date().toISOString(), dataSource: 'public-profile', dataNotice: 'Public TryHackMe profile data; APIVue does not verify account ownership.' };
  }
  const raw = handle.trim(); const match = raw.match(/(?:https?:\/\/)?(?:www\.)?profile\.hackthebox\.com\/profile\/([A-Za-z0-9-]{6,120})\/?$/i) ?? raw.match(/^([A-Za-z0-9-]{6,120})$/);
  if (!match) throw new Error('Enter a public Hack The Box profile URL or profile ID.'); const id = match[1]; const profileUrl = `https://profile.hackthebox.com/profile/${encodeURIComponent(id)}`;
  return { platform: 'hackthebox', handle: id, displayName: id, avatarUrl: null, profileUrl, bio: null, location: null, joinedAt: null, metrics: [], breakdowns: [], ratingHistory: [], activity: [], highlights: [{ title: 'Public HTB profile', subtitle: 'Open the platform profile to view published achievements and verified credentials.', url: profileUrl }], fetchedAt: new Date().toISOString(), dataSource: 'public-profile', dataNotice: 'HTB public profile link only. APIVue does not invent metrics or scrape private or undocumented APIs.' };
}
