import type { Goal } from '@/hooks/use-goals';
import type { ProfileSnapshot, TrackedProfile } from '@/lib/integrations/registry';
export type GoalTrackingMode='metric'|'activity'|'streak';
export type GoalTrackingPeriod='lifetime'|'daily';
export interface GoalTracking{mode:GoalTrackingMode;period:GoalTrackingPeriod;profileId?:string;metricKey?:string;baseline?:number;}
export interface GoalTrackerOption{id:string;mode:GoalTrackingMode;period:GoalTrackingPeriod;profileId?:string;metricKey?:string;label:string;description:string;value:number;unit:string;}
function metadataObject(goal:Goal):Record<string,unknown>{return goal.metadata&&typeof goal.metadata==='object'&&!Array.isArray(goal.metadata)?goal.metadata as Record<string,unknown>:{};}
export function getGoalTracking(goal:Goal):GoalTracking|null{const raw=metadataObject(goal).tracking;if(!raw||typeof raw!=='object'||Array.isArray(raw))return null;const t=raw as Record<string,unknown>;if(t.mode!=='metric'&&t.mode!=='activity'&&t.mode!=='streak')return null;return{mode:t.mode,period:t.period==='daily'?'daily':'lifetime',profileId:typeof t.profileId==='string'?t.profileId:undefined,metricKey:typeof t.metricKey==='string'?t.metricKey:undefined,baseline:typeof t.baseline==='number'&&Number.isFinite(t.baseline)?t.baseline:undefined};}
export function withGoalTracking(metadata:Goal['metadata'],tracking:GoalTracking):Goal['metadata']{const base=metadata&&typeof metadata==='object'&&!Array.isArray(metadata)?metadata as Record<string,unknown>:{};return{...base,tracking} as Goal['metadata'];}
function localDayKey(){const d=new Date();return`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;}
function previousDay(key:string){const d=new Date(`${key}T00:00:00`);d.setDate(d.getDate()-1);return`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;}
export function mergeGoalActivity(profiles:TrackedProfile[]){const map=new Map<string,number>();for(const p of profiles)for(const item of p.data?.activity??[]){if(!item?.date)continue;const key=item.date.slice(0,10);map.set(key,(map.get(key)??0)+Math.max(0,Number(item.count)||0));}return[...map.entries()].map(([date,count])=>({date,count})).sort((a,b)=>a.date.localeCompare(b.date));}
export function currentGoalStreak(profiles:TrackedProfile[]):number{const active=new Set(mergeGoalActivity(profiles).filter(x=>x.count>0).map(x=>x.date));let cursor=localDayKey();if(!active.has(cursor)){cursor=previousDay(cursor);if(!active.has(cursor))return 0;}let count=0;while(active.has(cursor)){count++;cursor=previousDay(cursor);}return count;}
function similarity(text:string,candidate:string){const tokens=text.toLowerCase().split(/[^a-z0-9]+/).filter(x=>x.length>2);return tokens.reduce((score,token)=>score+(candidate.includes(token)?1:0),0);}
export function inferLegacyTracking(goal:Goal,profiles:TrackedProfile[]):GoalTracking|null{const title=`${goal.title} ${goal.description??''} ${goal.unit??''}`.toLowerCase();if(/streak|consecutive|every day|daily/.test(title))return{mode:'activity',period:'daily'};const candidates:Array<{score:number;profile:TrackedProfile;key:string;value:number}>=[];for(const profile of profiles)for(const metric of profile.data?.metrics??[]){if(typeof metric.value!=='number'||!Number.isFinite(metric.value))continue;const candidate=`${metric.key} ${metric.label??''}`.toLowerCase();const score=similarity(title,candidate)+(goal.unit&&candidate.includes(goal.unit.toLowerCase())?2:0);candidates.push({score,profile,key:metric.key,value:metric.value});}candidates.sort((a,b)=>b.score-a.score);if(candidates[0]&&candidates[0].score>0)return{mode:'metric',period:'lifetime',profileId:candidates[0].profile.id,metricKey:candidates[0].key,baseline:candidates[0].value};if(profiles.some(p=>(p.data?.activity?.length??0)>0))return{mode:'activity',period:'lifetime'};return null;}
function metricValue(profile:TrackedProfile,key:string){const m=profile.data?.metrics?.find(x=>x.key===key);return m&&typeof m.value==='number'&&Number.isFinite(m.value)?m.value:null;}
export function resolveGoalValue(goal:Goal,profiles:TrackedProfile[],snapshots:ProfileSnapshot[]):number{const tracking=getGoalTracking(goal)??inferLegacyTracking(goal,profiles);if(!tracking)return Number.isFinite(goal.current_value)?goal.current_value:0;if(tracking.mode==='streak')return currentGoalStreak(profiles);const activity=mergeGoalActivity(profiles);if(tracking.mode==='activity'){if(tracking.period==='daily')return activity.find(x=>x.date===localDayKey())?.count??0;const start=goal.start_date?.slice(0,10);return activity.filter(x=>!start||x.date>=start).reduce((sum,x)=>sum+x.count,0);}if(tracking.metricKey){const candidates=profiles.filter(p=>!tracking.profileId||p.id===tracking.profileId);const values=candidates.map(p=>metricValue(p,tracking.metricKey!)).filter((v):v is number=>v!==null);if(values.length){const latest=Math.max(...values);const baseline=tracking.baseline??0;return tracking.period==='daily'?Math.max(0,latest-baseline):latest;}const snapshot=snapshots.filter(s=>!tracking.profileId||s.profile_id===tracking.profileId).sort((a,b)=>b.captured_at.localeCompare(a.captured_at)).find(s=>typeof s.metrics?.[tracking.metricKey!] === 'number');if(snapshot)return Number(snapshot.metrics[tracking.metricKey!]);}return Number.isFinite(goal.current_value)?goal.current_value:0;}
export function getGoalTrackerOptions(profiles:TrackedProfile[]):GoalTrackerOption[]{const options:GoalTrackerOption[]=[{id:'activity:daily',mode:'activity',period:'daily',label:'Daily activity',description:"Track today's recorded activity",value:0,unit:'events'},{id:'activity:lifetime',mode:'activity',period:'lifetime',label:'Recorded activity',description:'Track activity recorded since the goal started',value:0,unit:'events'},{id:'streak:lifetime',mode:'streak',period:'lifetime',label:'Current streak',description:'Track consecutive active days',value:currentGoalStreak(profiles),unit:'days'}];for(const profile of profiles)for(const metric of profile.data?.metrics??[]){if(typeof metric.value!=='number'||!Number.isFinite(metric.value))continue;options.push({id:`metric:${profile.id}:${metric.key}`,mode:'metric',period:'lifetime',profileId:profile.id,metricKey:metric.key,label:`${profile.platform} · ${metric.label??metric.key}`,description:`${profile.handle} · live profile metric`,value:metric.value,unit:metric.format==='percent'?'%':'value'});}return options;}
export function trackingId(tracking:GoalTracking|null){if(!tracking)return'manual';if(tracking.mode==='metric')return`metric:${tracking.profileId??''}:${tracking.metricKey??''}`;return`${tracking.mode}:${tracking.period}`;}
