import Link from "next/link";
import { ArrowRight, BarChart3, Braces, GitBranch, LockKeyhole, MoveRight } from "lucide-react";
import { platforms } from "@/config/platforms";

const pillars = [
  { icon: GitBranch, title: "Connect deliberately", text: "Start with a supported developer platform and see exactly which public capabilities are available." },
  { icon: BarChart3, title: "Understand the shape", text: "Normalize source responses into platform-specific metrics, trends, and comparisons." },
  { icon: Braces, title: "Keep requests visible", text: "Inspect safe public request details and generated examples without exposing credentials." },
];

export default function MarketingPage() {
  return <div className="marketing-page"><main><section className="hero"><div className="hero-copy"><p className="eyebrow">Developer intelligence, sourced</p><h1>Make APIs tell a clearer story.</h1><p className="hero-lede">APIVue turns developer-platform data into understandable analytics you can inspect, compare, and learn from.</p><div className="hero-actions"><Link className="button button-primary" href="/explore">Explore platforms <ArrowRight size={17} /></Link><Link className="button button-quiet" href="/docs">Read the model <MoveRight size={17} /></Link></div><div className="hero-note"><LockKeyhole size={15} /> Public requests are explainable. Private credentials stay protected.</div></div><div className="hero-console" aria-label="APIVue data flow"><div className="console-top"><span className="status-dot" /> pipeline / profile analytics <span>phase 01</span></div><div className="console-flow"><div className="flow-node active"><span>01</span><strong>Source</strong><small>GitHub API</small></div><div className="flow-line" /><div className="flow-node"><span>02</span><strong>Normalize</strong><small>profile model</small></div><div className="flow-line" /><div className="flow-node"><span>03</span><strong>Learn</strong><small>metrics + trends</small></div></div><div className="console-footer"><span>no live request made</span><span className="console-code">GET /user/events</span></div></div></section><section className="platform-strip"><div><p className="eyebrow">Supported sources</p><h2>Different platforms. Different questions.</h2></div><div className="platform-list">{platforms.map((platform) => <Link href={`/platforms/${platform.id}`} key={platform.id}><span>{platform.name}</span><small>{platform.category}</small></Link>)}</div></section><section className="pillars" id="capabilities">{pillars.map(({ icon: Icon, title, text }) => <article className="pillar" key={title}><Icon size={21} /><h3>{title}</h3><p>{text}</p></article>)}</section><section className="architecture"><div><p className="eyebrow">A useful separation</p><h2>Raw responses should not become UI by accident.</h2><p>Integrations fetch. Normalizers translate. Analytics calculate. Visualizations explain. That boundary lets each platform keep its own vocabulary while APIVue shares reliable infrastructure.</p><Link className="text-link" href="/docs">See the architecture &rarr;</Link></div><div className="layers"><span>Visualization</span><span>Analytics engine</span><span>Normalized profile</span><span>Raw response</span></div></section></main></div>;
}
