"use client";

import { useState } from "react";
import type { AnalyticsResult, NormalizedProfile } from "@/types";
import { BarChart, LineChart, StatCard } from "@/components/analytics/charts";
import { JsonViewer } from "@/components/json-viewer/json-viewer";

type ProfilePayload = { profile: NormalizedProfile; analytics: AnalyticsResult; source: string; documentation: string; limitations?: string; fetchedAt: string; durationMs: number; raw: unknown };

function distributionData(result: AnalyticsResult, id: string): [string, number][] { return result.distributions.find(distribution => distribution.id === id)?.entries.map(entry => [entry.label, entry.count] as [string, number]) ?? []; }

export function ProfileExperience({ platform }: { platform: "github" | "codeforces" }) {
  const [username, setUsername] = useState(""); const [data, setData] = useState<ProfilePayload | null>(null); const [error, setError] = useState<string | null>(null); const [busy, setBusy] = useState(false);
  const fetchProfile = async (event: React.FormEvent) => { event.preventDefault(); setBusy(true); setError(null); setData(null); try { const response = await fetch(`/api/profiles/${platform}?username=${encodeURIComponent(username)}`); const body = await response.json() as ProfilePayload & { error?: string }; if (!response.ok) throw new Error(body.error ?? "Profile data could not be loaded."); setData(body); } catch (caught) { setError(caught instanceof Error ? caught.message : "Profile data could not be loaded."); } finally { setBusy(false); } };
  const labels = platform === "github" ? "GitHub username" : "Codeforces handle";
  return <section className="profile-experience"><form className="profile-form" onSubmit={fetchProfile}><label>{labels}<input value={username} onChange={event => setUsername(event.target.value)} required placeholder={platform === "github" ? "octocat" : "tourist"} /></label><button className="button button-primary" disabled={busy}>{busy ? "Loading source..." : "Fetch public profile"}</button></form>{busy && <div className="empty-state" aria-live="polite">Fetching current public data from {platform}...</div>}{error && <div className="error-state" role="alert">{error}</div>}{data && <div className="profile-result"><header className="profile-source"><div><p className="section-label">Live public profile</p><h2>{data.profile.displayName}</h2></div><a className="text-link" href={data.profile.profileUrl}>Open source profile ↗</a></header><div className="stats-grid">{data.profile.metrics.map(metric => <StatCard key={metric.id} label={metric.label} value={metric.value} />)}</div>{platform === "github" ? <><BarChart title="Language distribution by public repositories" data={distributionData(data.analytics, "languages").slice(0, 10)} /><BarChart title="Most-starred public repositories" data={data.analytics.rankings.find(ranking => ranking.id === "repositories")?.entries.map(entry => [entry.label, entry.value] as [string, number]) ?? []} /></> : <><LineChart title="Rating timeline" data={data.analytics.timeSeries.find(series => series.id === "rating-history")?.points ?? []} /><div className="chart-grid"><BarChart title="Accepted problem difficulty" data={distributionData(data.analytics, "difficulty")} /><BarChart title="Most frequent accepted tags" data={distributionData(data.analytics, "tags")} /></div><section className="recent-submissions"><h3>Submission analytics</h3><p className="muted">{data.analytics.metrics.find(metric => metric.id === "accepted-submissions")?.value ?? "Unavailable"} accepted submissions in the fetched public sample.</p></section></>}<details><summary>How this data was fetched</summary><p>Source: {data.source} · {data.durationMs} ms · fetched {new Date(data.fetchedAt).toLocaleString()}</p>{data.limitations ? <p className="muted">Limitation: {data.limitations}</p> : null}<a className="text-link" href={data.documentation}>View official documentation ↗</a></details><details><summary>Analytics notes</summary><p>{data.analytics.metadata.calculations.join(" ")}</p>{data.analytics.warnings.map(warning => <p className="muted" key={warning.code}>{warning.code}: {warning.message}</p>)}</details><details><summary>Raw source response</summary><JsonViewer value={data.raw} /></details></div>}</section>;
}
