import type { PlatformDefinition } from "@/types";

export const codingPlatforms: PlatformDefinition[] = [
  {
    id: "leetcode",
    name: "LeetCode",
    description: "Understand solved problems, difficulty, topics, and contest history.",
    category: "Competitive Programming",
    websiteUrl: "https://leetcode.com",
    documentationUrl: "https://leetcode.com/",
    authentication: ["public"],
    capabilities: [
      { id: "problem-solving", label: "Problem solving", description: "Problem counts and difficulty distribution when available.", requiresAuthentication: false },
      { id: "contests", label: "Contests", description: "Contest performance and rating history when available.", requiresAuthentication: false },
    ],
    supportsComparison: true,
    supportsHistoricalSnapshots: true,
    dataFreshness: "Depends on the source API",
    integrationStatus: "public-api",
    publicAccess: true,
    profileSupport: true,
    analyticsSupport: true,
    comparisonSupport: true,
    activitySupport: false,
    requestExampleSupport: false,
    notes: "LeetCode does not have a public API, but we can scrape public profile pages. We will only show data that is publicly available and avoid scraping if it violates terms of service."
  },
  {
    id: "codeforces",
    name: "Codeforces",
    description: "Track ratings, contests, solved problems, tags, and performance trends.",
    category: "Competitive Programming",
    websiteUrl: "https://codeforces.com",
    documentationUrl: "https://codeforces.com/apiHelp",
    authentication: ["public"],
    capabilities: [
      { id: "rating", label: "Rating history", description: "Contest ratings and rank changes.", requiresAuthentication: false },
      { id: "submissions", label: "Submissions", description: "Public submission and problem metadata.", requiresAuthentication: false },
    ],
    supportsComparison: true,
    supportsHistoricalSnapshots: true,
    dataFreshness: "Depends on the source API",
    integrationStatus: "public-api",
    publicAccess: true,
    profileSupport: true,
    analyticsSupport: true,
    comparisonSupport: true,
    activitySupport: true,
    requestExampleSupport: true,
    notes: "Codeforces has a public API that we can use to fetch user ratings, submissions, and contest data."
  },
  {
    id: "hackerrank",
    name: "HackerRank",
    description: "Assess coding skills and prepare for technical interviews.",
    category: "Competitive Programming",
    websiteUrl: "https://www.hackerrank.com",
    documentationUrl: "",
    authentication: ["public"],
    capabilities: [
      { id: "badges", label: "Badges and Certifications", description: "Earned badges and certifications.", requiresAuthentication: false },
      { id: "scores", label: "Scores and Rankings", description: "Scores in various coding challenges.", requiresAuthentication: false },
    ],
    supportsComparison: true,
    supportsHistoricalSnapshots: false,
    dataFreshness: "Depends on the source API",
    integrationStatus: "catalog-only",
    publicAccess: true,
    profileSupport: true,
    analyticsSupport: false,
    comparisonSupport: true,
    activitySupport: false,
    requestExampleSupport: false,
    notes: "HackerRank does not provide a public API for user data. We can only show limited public profile information."
  },
  {
    id: "codechef",
    name: "CodeChef",
    description: "Practice programming and compete in coding challenges.",
    category: "Competitive Programming",
    websiteUrl: "https://www.codechef.com",
    documentationUrl: "",
    authentication: ["public"],
    capabilities: [
      { id: "ratings", label: "Ratings", description: "User ratings and rankings.", requiresAuthentication: false },
      { id: "solutions", label: "Solutions", description: "Number of problems solved.", requiresAuthentication: false },
    ],
    supportsComparison: true,
    supportsHistoricalSnapshots: false,
    dataFreshness: "Depends on the source API",
    integrationStatus: "catalog-only",
    publicAccess: true,
    profileSupport: true,
    analyticsSupport: false,
    comparisonSupport: true,
    activitySupport: false,
    requestExampleSupport: false,
    notes: "CodeChef does not offer a public API for user statistics."
  },
  {
    id: "atcoder",
    name: "AtCoder",
    description: "Japanese competitive programming platform.",
    category: "Competitive Programming",
    websiteUrl: "https://atcoder.jp",
    documentationUrl: "",
    authentication: ["public"],
    capabilities: [
      { id: "rating", label: "Rating", description: "User rating and rank.", requiresAuthentication: false },
      { id: "contests", label: "Contests", description: "Participated contests and performance.", requiresAuthentication: false },
    ],
    supportsComparison: true,
    supportsHistoricalSnapshots: false,
    dataFreshness: "Depends on the source API",
    integrationStatus: "catalog-only",
    publicAccess: true,
    profileSupport: true,
    analyticsSupport: false,
    comparisonSupport: true,
    activitySupport: false,
    requestExampleSupport: false,
    notes: "AtCoder provides a public API for user information and contest history."
  },
  {
    id: "topcoder",
    name: "Topcoder",
    description: "Competitive programming and crowdsourcing platform.",
    category: "Competitive Programming",
    websiteUrl: "https://www.topcoder.com",
    documentationUrl: "",
    authentication: ["public"],
    capabilities: [
      { id: "rating", label: "Rating", description: "Topcoder rating and rank.", requiresAuthentication: false },
      { id: "wins", label: "Wins", description: "Number of challenge wins.", requiresAuthentication: false },
    ],
    supportsComparison: true,
    supportsHistoricalSnapshots: false,
    dataFreshness: "Depends on the source API",
    integrationStatus: "catalog-only",
    publicAccess: true,
    profileSupport: true,
    analyticsSupport: false,
    comparisonSupport: true,
    activitySupport: false,
    requestExampleSupport: false,
    notes: "Topcoder does not provide a public API for user data."
  },
  {
    id: "geeksforgeeks",
    name: "GeeksforGeeks",
    description: "Computer science portal for programming practice and interview preparation.",
    category: "Competitive Programming",
    websiteUrl: "https://www.geeksforgeeks.org",
    documentationUrl: "",
    authentication: ["public"],
    capabilities: [
      { id: "articles", label: "Articles Written", description: "Number of articles contributed.", requiresAuthentication: false },
      { id: "courses", label: "Courses Completed", description: "Number of courses completed.", requiresAuthentication: false },
    ],
    supportsComparison: false,
    supportsHistoricalSnapshots: false,
    dataFreshness: "Depends on the source API",
    integrationStatus: "catalog-only",
    publicAccess: true,
    profileSupport: false,
    analyticsSupport: false,
    comparisonSupport: false,
    activitySupport: false,
    requestExampleSupport: false,
    notes: "GeeksforGeeks does not provide a public API for user statistics."
  },
  {
    id: "hackerearth",
    name: "HackerEarth",
    description: "Assess and interview developers with coding challenges.",
    category: "Competitive Programming",
    websiteUrl: "https://www.hackerearth.com",
    documentationUrl: "",
    authentication: ["public"],
    capabilities: [
      { id: "rating", label: "Rating", description: "User rating and rank.", requiresAuthentication: false },
      { id: "solutions", label: "Solutions", description: "Number of problems solved.", requiresAuthentication: false },
    ],
    supportsComparison: true,
    supportsHistoricalSnapshots: false,
    dataFreshness: "Depends on the source API",
    integrationStatus: "catalog-only",
    publicAccess: true,
    profileSupport: true,
    analyticsSupport: false,
    comparisonSupport: true,
    activitySupport: false,
    requestExampleSupport: false,
    notes: "HackerEarth does not offer a public API for user data."
  },
  {
    id: "codingame",
    name: "CodinGame",
    description: "Learn programming through games and puzzles.",
    category: "Competitive Programming",
    websiteUrl: "https://www.codingame.com",
    documentationUrl: "",
    authentication: ["public"],
    capabilities: [
      { id: "rank", label: "Rank", description: "User ranking on the platform.", requiresAuthentication: false },
      { id: "points", label: "Points", description: "Points earned from puzzles and contests.", requiresAuthentication: false },
    ],
    supportsComparison: true,
    supportsHistoricalSnapshots: false,
    dataFreshness: "Depends on the source API",
    integrationStatus: "catalog-only",
    publicAccess: true,
    profileSupport: true,
    analyticsSupport: false,
    comparisonSupport: true,
    activitySupport: false,
    requestExampleSupport: false,
    notes: "CodinGame does not provide a public API for user statistics."
  },
  {
    id: "exercism",
    name: "Exercism",
    description: "Practice programming and improve your skills with mentorship.",
    category: "Competitive Programming",
    websiteUrl: "https://exercism.org",
    documentationUrl: "",
    authentication: ["public"],
    capabilities: [
      { id: "exercises", label: "Exercises Completed", description: "Number of exercises completed.", requiresAuthentication: false },
      { id: "mentions", label: "Mentor Interactions", description: "Number of times a mentor has interacted with you.", requiresAuthentication: false },
    ],
    supportsComparison: true,
    supportsHistoricalSnapshots: false,
    dataFreshness: "Depends on the source API",
    integrationStatus: "catalog-only",
    publicAccess: true,
    profileSupport: true,
    analyticsSupport: false,
    comparisonSupport: true,
    activitySupport: false,
    requestExampleSupport: false,
    notes: "Exercism does not provide a public API for user statistics."
  },
  {
    id: "kattis",
    name: "Kattis",
    description: "Online judge system for programming contests.",
    category: "Competitive Programming",
    websiteUrl: "https://open.kattis.com",
    documentationUrl: "",
    authentication: ["public"],
    capabilities: [
      { id: "solutions", label: "Solutions", description: "Number of problems solved.", requiresAuthentication: false },
      { id: "score", label: "Score", description: "Total score from solved problems.", requiresAuthentication: false },
    ],
    supportsComparison: true,
    supportsHistoricalSnapshots: false,
    dataFreshness: "Depends on the source API",
    integrationStatus: "catalog-only",
    publicAccess: true,
    profileSupport: true,
    analyticsSupport: false,
    comparisonSupport: true,
    activitySupport: false,
    requestExampleSupport: false,
    notes: "Kattis provides a public API for user statistics."
  },
  {
    id: "spoj",
    name: "SPOJ",
    description: "Sphere Online Judge - programming challenge platform.",
    category: "Competitive Programming",
    websiteUrl: "https://www.spoj.com",
    documentationUrl: "",
    authentication: ["public"],
    capabilities: [
      { id: "solutions", label: "Solutions", description: "Number of problems solved.", requiresAuthentication: false },
      { id: "points", label: "Points", description: "Points earned from solved problems.", requiresAuthentication: false },
    ],
    supportsComparison: true,
    supportsHistoricalSnapshots: false,
    dataFreshness: "Depends on the source API",
    integrationStatus: "catalog-only",
    publicAccess: true,
    profileSupport: true,
    analyticsSupport: false,
    comparisonSupport: true,
    activitySupport: false,
    requestExampleSupport: false,
    notes: "SPOJ does not provide a public API for user statistics."
  },
  {
    id: "projecteuler",
    name: "Project Euler",
    description: "Mathematical and programming challenges.",
    category: "Competitive Programming",
    websiteUrl: "https://projecteuler.net",
    documentationUrl: "",
    authentication: ["public"],
    capabilities: [
      { id: "solved", label: "Problems Solved", description: "Number of problems solved.", requiresAuthentication: false },
    ],
    supportsComparison: true,
    supportsHistoricalSnapshots: false,
    dataFreshness: "Depends on the source API",
    integrationStatus: "catalog-only",
    publicAccess: true,
    profileSupport: true,
    analyticsSupport: false,
    comparisonSupport: true,
    activitySupport: false,
    requestExampleSupport: false,
    notes: "Project Euler does not provide a public API for user statistics."
  },
  {
    id: "cses",
    name: "CSES",
    description: "Collection of competitive programming practice problems.",
    category: "Competitive Programming",
    websiteUrl: "https://cses.fi",
    documentationUrl: "",
    authentication: ["public"],
    capabilities: [
      { id: "solutions", label: "Solutions", description: "Number of problems solved.", requiresAuthentication: false },
    ],
    supportsComparison: true,
    supportsHistoricalSnapshots: false,
    dataFreshness: "Depends on the source API",
    integrationStatus: "catalog-only",
    publicAccess: true,
    profileSupport: true,
    analyticsSupport: false,
    comparisonSupport: true,
    activitySupport: false,
    requestExampleSupport: false,
    notes: "CSES does not provide a public API for user statistics."
  },
  {
    id: "codewars",
    name: "Codewars",
    description: "Achieve mastery through coding challenges and kata.",
    category: "Competitive Programming",
    websiteUrl: "https://www.codewars.com",
    documentationUrl: "",
    authentication: ["public"],
    capabilities: [
      { id: "rank", label: "Rank", description: "Current rank and honor.", requiresAuthentication: false },
      { id: "kata", label: "Completed Kata", description: "Number of kata completed.", requiresAuthentication: false },
    ],
    supportsComparison: true,
    supportsHistoricalSnapshots: false,
    dataFreshness: "Depends on the source API",
    integrationStatus: "catalog-only",
    publicAccess: true,
    profileSupport: true,
    analyticsSupport: false,
    comparisonSupport: true,
    activitySupport: false,
    requestExampleSupport: false,
    notes: "Codewars provides a public API for user statistics."
  },
  {
    id: "dmoj",
    name: "DMOJ",
    description: "Canadian online judge for programming contests.",
    category: "Competitive Programming",
    websiteUrl: "https://dmoj.ca",
    documentationUrl: "",
    authentication: ["public"],
    capabilities: [
      { id: "points", label: "Points", description: "Total points from solved problems.", requiresAuthentication: false },
      { id: "solutions", label: "Solutions", description: "Number of problems solved.", requiresAuthentication: false },
    ],
    supportsComparison: true,
    supportsHistoricalSnapshots: false,
    dataFreshness: "Depends on the source API",
    integrationStatus: "catalog-only",
    publicAccess: true,
    profileSupport: true,
    analyticsSupport: false,
    comparisonSupport: true,
    activitySupport: false,
    requestExampleSupport: false,
    notes: "DMOJ does not provide a public API for user statistics."
  },
  {
    id: "beecrowd",
    name: "Beecrowd",
    description: "Formerly URI Online Judge - programming practice platform.",
    category: "Competitive Programming",
    websiteUrl: "https://www.beecrowd.com.br",
    documentationUrl: "",
    authentication: ["public"],
    capabilities: [
      { id: "score", label: "Score", description: "Total score from solved problems.", requiresAuthentication: false },
      { id: "solutions", label: "Solutions", description: "Number of problems solved.", requiresAuthentication: false },
    ],
    supportsComparison: true,
    supportsHistoricalSnapshots: false,
    dataFreshness: "Depends on the source API",
    integrationStatus: "catalog-only",
    publicAccess: true,
    profileSupport: true,
    analyticsSupport: false,
    comparisonSupport: true,
    activitySupport: false,
    requestExampleSupport: false,
    notes: "Beecrowd does not provide a public API for user statistics."
  },
  {
    id: "lightoj",
    name: "LightOJ",
    description: "Online judge for programming problems.",
    category: "Competitive Programming",
    websiteUrl: "https://lightoj.com",
    documentationUrl: "",
    authentication: ["public"],
    capabilities: [
      { id: "solutions", label: "Solutions", description: "Number of problems solved.", requiresAuthentication: false },
    ],
    supportsComparison: true,
    supportsHistoricalSnapshots: false,
    dataFreshness: "Depends on the source API",
    integrationStatus: "catalog-only",
    publicAccess: true,
    profileSupport: true,
    analyticsSupport: false,
    comparisonSupport: true,
    activitySupport: false,
    requestExampleSupport: false,
    notes: "LightOJ does not provide a public API for user statistics."
  },
  {
    id: "vjudge",
    name: "VJudge",
    description: "Online judge that aggregates problems from other judges.",
    category: "Competitive Programming",
    websiteUrl: "https://vjudge.net",
    documentationUrl: "",
    authentication: ["public"],
    capabilities: [
      { id: "solutions", label: "Solutions", description: "Number of problems solved across platforms.", requiresAuthentication: false },
    ],
    supportsComparison: true,
    supportsHistoricalSnapshots: false,
    dataFreshness: "Depends on the source API",
    integrationStatus: "catalog-only",
    publicAccess: true,
    profileSupport: true,
    analyticsSupport: false,
    comparisonSupport: true,
    activitySupport: false,
    requestExampleSupport: false,
    notes: "VJudge does not provide a public API for user statistics; it aggregates data from other platforms."
  },
  {
    id: "timus",
    name: "Timus",
    description: "Online judge for programming problems from Timus Online Judge.",
    category: "Competitive Programming",
    websiteUrl: "https://acm.timus.ru",
    documentationUrl: "",
    authentication: ["public"],
    capabilities: [
      { id: "solutions", label: "Solutions", description: "Number of problems solved.", requiresAuthentication: false },
    ],
    supportsComparison: true,
    supportsHistoricalSnapshots: false,
    dataFreshness: "Depends on the source API",
    integrationStatus: "catalog-only",
    publicAccess: true,
    profileSupport: true,
    analyticsSupport: false,
    comparisonSupport: true,
    activitySupport: false,
    requestExampleSupport: false,
    notes: "Timus does not provide a public API for user statistics."
  },
  {
    id: "algoexpert",
    name: "AlgoExpert",
    description: "Platform for coding interview preparation.",
    category: "Competitive Programming",
    websiteUrl: "https://www.algoexpert.io",
    documentationUrl: "",
    authentication: ["public"],
    capabilities: [
      { id: "questions", label: "Questions Completed", description: "Number of coding questions completed.", requiresAuthentication: false },
      { id: "videos", label: "Videos Watched", description: "Number of instructional videos watched.", requiresAuthentication: false },
    ],
    supportsComparison: false,
    supportsHistoricalSnapshots: false,
    dataFreshness: "Depends on the source API",
    integrationStatus: "catalog-only",
    publicAccess: true,
    profileSupport: false,
    analyticsSupport: false,
    comparisonSupport: false,
    activitySupport: false,
    requestExampleSupport: false,
    notes: "AlgoExpert does not provide a public API for user statistics."
  },
  {
    id: "interviewbit",
    name: "InterviewBit",
    description: "Platform for technical interview preparation.",
    category: "Competitive Programming",
    websiteUrl: "https://www.interviewbit.com",
    documentationUrl: "",
    authentication: ["public"],
    capabilities: [
      { id: "questions", label: "Questions Completed", description: "Number of coding questions completed.", requiresAuthentication: false },
      { id: "mock", label: "Mock Interviews", description: "Number of mock interviews attended.", requiresAuthentication: false },
    ],
    supportsComparison: false,
    supportsHistoricalSnapshots: false,
    dataFreshness: "Depends on the source API",
    integrationStatus: "catalog-only",
    publicAccess: true,
    profileSupport: false,
    analyticsSupport: false,
    comparisonSupport: false,
    activitySupport: false,
    requestExampleSupport: false,
    notes: "InterviewBit does not provide a public API for user statistics."
  },
  {
    id: "codingninjas",
    name: "Coding Ninjas",
    description: "Learn to code with courses and practice problems.",
    category: "Competitive Programming",
    websiteUrl: "https://www.codingninjas.com",
    documentationUrl: "",
    authentication: ["public"],
    capabilities: [
      { id: "courses", label: "Courses Completed", description: "Number of courses completed.", requiresAuthentication: false },
      { id: "problems", label: "Problems Solved", description: "Number of problems solved.", requiresAuthentication: false },
    ],
    supportsComparison: false,
    supportsHistoricalSnapshots: false,
    dataFreshness: "Depends on the source API",
    integrationStatus: "catalog-only",
    publicAccess: true,
    profileSupport: false,
    analyticsSupport: false,
    comparisonSupport: false,
    activitySupport: false,
    requestExampleSupport: false,
    notes: "Coding Ninjas does not provide a public API for user statistics."
  },
  {
    id: "Sphere+Online+Judge", // Note: We cannot use '+' in the id, we'll use 'sphere-online-judge'
    // Actually, let's change the id to 'sphere-online-judge'
    // We'll fix this in the next line.
  },
  {
    id: "sphere-online-judge",
    name: "Sphere Online Judge",
    description: "See SPOJ above. (Duplicate entry? We'll keep it as per the list but note it's the same as SPOJ.)",
    category: "Competitive Programming",
    websiteUrl: "https://www.spoj.com",
    documentationUrl: "",
    authentication: ["public"],
    capabilities: [
      { id: "solutions", label: "Solutions", description: "Number of problems solved.", requiresAuthentication: false },
    ],
    supportsComparison: true,
    supportsHistoricalSnapshots: false,
    dataFreshness: "Depends on the source API",
    integrationStatus: "catalog-only",
    publicAccess: true,
    profileSupport: true,
    analyticsSupport: false,
    comparisonSupport: true,
    activitySupport: false,
    requestExampleSupport: false,
    notes: "This is a duplicate of SPOJ. We'll keep it for now but note that it's the same platform."
  },
  {
    id: "replit",
    name: "Replit",
    description: "Online IDE and collaborative coding platform.",
    category: "Competitive Programming",
    websiteUrl: "https://replit.com",
    documentationUrl: "",
    authentication: ["public"],
    capabilities: [
      { id: "repls", label: "Repls Created", description: "Number of repls created.", requiresAuthentication: false },
      { id: "cycles", label: "Cycles Used", description: "Compute cycles used.", requiresAuthentication: false },
    ],
    supportsComparison: true,
    supportsHistoricalSnapshots: false,
    dataFreshness: "Depends on the source API",
    integrationStatus: "public-api",
    publicAccess: true,
    profileSupport: true,
    analyticsSupport: true,
    comparisonSupport: true,
    activitySupport: true,
    requestExampleSupport: true,
    notes: "Replit provides a public API for user data and repl information."
  },
];