import type { PlatformDefinition } from "@/types";

export const gitPlatforms: PlatformDefinition[] = [
  {
    id: "github",
    name: "GitHub",
    description: "Explore repositories, languages, and public contribution activity.",
    category: "git",
    websiteUrl: "https://github.com",
    documentationUrl: "https://docs.github.com/en/rest",
    authentication: ["public", "oauth2"],
    capabilities: [
      { id: "repositories", label: "Repositories", description: "Public repository and language data.", requiresAuthentication: false },
      { id: "activity", label: "Activity", description: "Public contribution and event activity.", requiresAuthentication: false },
    ],
    supportsComparison: true,
    supportsHistoricalSnapshots: true,
    dataFreshness: "Depends on the source API",
  },
  {
    id: "gitlab",
    name: "GitLab",
    description: "DevOps platform for project planning, source code management, CI/CD, and monitoring.",
    category: "git",
    websiteUrl: "https://gitlab.com",
    documentationUrl: "https://docs.gitlab.com/ee/api/",
    authentication: ["public", "oauth2"],
    capabilities: [
      { id: "repositories", label: "Repositories", description: "Public repository and language data.", requiresAuthentication: false },
      { id: "activity", label: "Activity", description: "Public contribution and event activity.", requiresAuthentication: false },
      { id: "merge_requests", label: "Merge Requests", description: "Merge requests and discussions.", requiresAuthentication: true },
    ],
    supportsComparison: true,
    supportsHistoricalSnapshots: true,
    dataFreshness: "Depends on the source API",
  },
  {
    id: "bitbucket",
    name: "Bitbucket",
    description: "Git-based code hosting and collaboration tool.",
    category: "git",
    websiteUrl: "https://bitbucket.org",
    documentationUrl: "https://developer.atlassian.com/cloud/bitbucket/rest/api-group-repositories/",
    authentication: ["public", "oauth2"],
    capabilities: [
      { id: "repositories", label: "Repositories", description: "Public repository and language data.", requiresAuthentication: false },
      { id: "pull_requests", label: "Pull Requests", description: "Pull requests and discussions.", requiresAuthentication: true },
    ],
    supportsComparison: true,
    supportsHistoricalSnapshots: true,
    dataFreshness: "Depends on the source API",
  },
  {
    id: "codeberg",
    name: "Codeberg",
    description: "Non-profit focused code hosting platform based on Gitea.",
    category: "git",
    websiteUrl: "https://codeberg.org",
    documentationUrl: "https://docs.codeberg.org/",
    authentication: ["public", "oauth2"],
    capabilities: [
      { id: "repositories", label: "Repositories", description: "Public repository and language data.", requiresAuthentication: false },
    ],
    supportsComparison: true,
    supportsHistoricalSnapshots: true,
    dataFreshness: "Depends on the source API",
  },
  {
    id: "sourceforge",
    name: "SourceForge",
    description: "Web-based service that offers developers a centralized online location to control and manage free and open-source software projects.",
    category: "git",
    websiteUrl: "https://sourceforge.net",
    documentationUrl: "",
    authentication: ["public"],
    capabilities: [
      { id: "repositories", label: "Repositories", description: "Public repository data (if available).", requiresAuthentication: false },
    ],
    supportsComparison: false,
    supportsHistoricalSnapshots: false,
    dataFreshness: "Depends on the source API",
    integrationStatus: "catalog-only",
  },
  {
    id: "gitea",
    name: "Gitea",
    description: "Painless self-hosted Git service.",
    category: "git",
    websiteUrl: "https://gitea.io",
    documentationUrl: "https://docs.gitea.io/en-us/",
    authentication: ["public", "oauth2"],
    capabilities: [
      { id: "repositories", label: "Repositories", description: "Public repository and language data.", requiresAuthentication: false },
    ],
    supportsComparison: true,
    supportsHistoricalSnapshots: true,
    dataFreshness: "Depends on the source API",
  },
  {
    id: "gitee",
    name: "Gitee",
    description: "Git-based code hosting and research development platform.",
    category: "git",
    websiteUrl: "https://gitee.com",
    documentationUrl: "",
    authentication: ["public"],
    capabilities: [
      { id: "repositories", label: "Repositories", description: "Public repository and language data.", requiresAuthentication: false },
    ],
    supportsComparison: true,
    supportsHistoricalSnapshots: true,
    dataFreshness: "Depends on the source API",
    integrationStatus: "catalog-only",
  },
  {
    id: "azure-devops",
    name: "Azure DevOps",
    description: "Developer services for planning, collaborating, and building applications.",
    category: "git",
    websiteUrl: "https://azure.microsoft.com/en-us/services/devops/",
    documentationUrl: "https://learn.microsoft.com/en-us/rest/api/azure/devops/",
    authentication: ["public", "oauth2"],
    capabilities: [
      { id: "repositories", label: "Repositories", description: "Public repository and language data.", requiresAuthentication: false },
      { id: "pull_requests", label: "Pull Requests", description: "Pull requests and discussions.", requiresAuthentication: true },
    ],
    supportsComparison: true,
    supportsHistoricalSnapshots: true,
    dataFreshness: "Depends on the source API",
  },
  {
    id: "aws-codecommit",
    name: "AWS CodeCommit",
    description: "Secure, highly scalable, managed source control service that hosts private Git repositories.",
    category: "git",
    websiteUrl: "https://aws.amazon.com/codecommit/",
    documentationUrl: "https://docs.aws.amazon.com/codecommit/latest/APIReference/",
    authentication: ["public", "api-key"],
    capabilities: [
      { id: "repositories", label: "Repositories", description: "Public repository and language data (if available).", requiresAuthentication: false },
    ],
    supportsComparison: false,
    supportsHistoricalSnapshots: false,
    dataFreshness: "Depends on the source API",
    integrationStatus: "authenticated",
  },
  {
    id: "launchpad",
    name: "Launchpad",
    description: "Software collaboration platform by Canonical.",
    category: "git",
    websiteUrl: "https://launchpad.net",
    documentationUrl: "",
    authentication: ["public"],
    capabilities: [
      { id: "repositories", label: "Repositories", description: "Public repository data (if available).", requiresAuthentication: false },
    ],
    supportsComparison: false,
    supportsHistoricalSnapshots: false,
    dataFreshness: "Depends on the source API",
    integrationStatus: "catalog-only",
  },
  {
    id: "sourcehut",
    name: "SourceHut",
    description: "Simple, secure, and flexible forge for software development.",
    category: "git",
    websiteUrl: "https://sourcehut.org",
    documentationUrl: "https://sourcehut.org/git/",
    authentication: ["public", "oauth2"],
    capabilities: [
      { id: "repositories", label: "Repositories", description: "Public repository and language data.", requiresAuthentication: false },
    ],
    supportsComparison: true,
    supportsHistoricalSnapshots: true,
    dataFreshness: "Depends on the source API",
  },
  {
    id: "phabricator",
    name: "Phabricator",
    description: "Open-source software engineering platform.",
    category: "git",
    websiteUrl: "https://phacility.com/phabricator/",
    documentationUrl: "",
    authentication: ["public"],
    capabilities: [
      { id: "repositories", label: "Repositories", description: "Public repository data (if available).", requiresAuthentication: false },
    ],
    supportsComparison: false,
    supportsHistoricalSnapshots: false,
    dataFreshness: "Depends on the source API",
    integrationStatus: "catalog-only",
  },
  {
    id: "pagure",
    name: "Pagure",
    description: "Lightweight Git-centered forge for Fedora and other community projects.",
    category: "git",
    websiteUrl: "https://pagure.io",
    documentationUrl: "",
    authentication: ["public"],
    capabilities: [
      { id: "repositories", label: "Repositories", description: "Public repository data (if available).", requiresAuthentication: false },
    ],
    supportsComparison: false,
    supportsHistoricalSnapshots: false,
    dataFreshness: "Depends on the source API",
    integrationStatus: "catalog-only",
  },
  {
    id: "gerrit",
    name: "Gerrit",
    description: "Web-based team code collaboration tool.",
    category: "git",
    websiteUrl: "https://www.gerritcodereview.com/",
    documentationUrl: "https://gerrit-review.googlesource.com/Documentation/rest-api.html",
    authentication: ["public", "http"],
    capabilities: [
      { id: "repositories", label: "Repositories", description: "Public repository and language data.", requiresAuthentication: false },
    ],
    supportsComparison: true,
    supportsHistoricalSnapshots: true,
    dataFreshness: "Depends on the source API",
  },
  {
    id: "savannah",
    name: "Savannah",
    description: "Free software development and hosting system.",
    category: "git",
    websiteUrl: "https://savannah.gnu.org",
    documentationUrl: "",
    authentication: ["public"],
    capabilities: [
      { id: "repositories", label: "Repositories", description: "Public repository data (if available).", requiresAuthentication: false },
    ],
    supportsComparison: false,
    supportsHistoricalSnapshots: false,
    dataFreshness: "Depends on the source API",
    integrationStatus: "catalog-only",
  },
];