import { NextRequest, NextResponse } from "next/server";
import { normalizeGitHub } from "@/lib/integrations/github/normalizer";
import { normalizeCodeforces } from "@/lib/integrations/codeforces/normalizer";
const json = async (url: string) => { const response = await fetch(url,{headers:{Accept:"application/json","User-Agent":"APIVue/0.2 public analytics"},next:{revalidate:60}}); const text=await response.text(); let data: any; try { data=JSON.parse(text); } catch { data={message:"The source returned an invalid response."}; } if(!response.ok) { const reset=response.headers.get("x-ratelimit-reset"); const retry=response.headers.get("retry-after") || (reset ? String(Math.max(0, Number(reset)-Math.floor(Date.now()/1000))) : null); throw Object.assign(new Error(data.message || "The source returned an error."),{status:response.status,rate:retry}); } return data; };
export async function GET(request: NextRequest,{params}:{params:{platform:string}}) { const username=request.nextUrl.searchParams.get("username")?.trim(); if(!username || username.length>80) return NextResponse.json({error:"Enter a valid public username."},{status:400}); const start=Date.now(); try {
  if(params.platform === "github") { const root="https://api.github.com/users/"+encodeURIComponent(username); const [user,repositories,events]=await Promise.all([json(root),json(root+"/repos?per_page=100&sort=updated"),json(root+"/events/public?per_page=100")]); const profile=normalizeGitHub(user,repositories,events); return NextResponse.json({profile,raw:{user,repositories,events},analytics:{languages:Object.entries(repositories.reduce((m:any,r:any)=>{if(r.language)m[r.language]=(m[r.language]||0)+1;return m;},{})),topRepositories:[...repositories].sort((a:any,b:any)=>b.stargazers_count-a.stargazers_count).slice(0,8),activity:events.map((event:any)=>({type:event.type,createdAt:event.created_at,repo:event.repo?.name}))},source:"GitHub REST API",documentation:"https://docs.github.com/en/rest",limitations:"Repository-derived aggregates are calculated from the latest 100 public repositories returned by this request.",fetchedAt:new Date().toISOString(),durationMs:Date.now()-start}); }
  if(params.platform === "codeforces") { const base="https://codeforces.com/api/"; const [info,rating,submissions]=await Promise.all([json(base+"user.info?handles="+encodeURIComponent(username)),json(base+"user.rating?handle="+encodeURIComponent(username)),json(base+"user.status?handle="+encodeURIComponent(username)+"&from=1&count=1000")]); if(info.status!=="OK"||rating.status!=="OK"||submissions.status!=="OK") throw Object.assign(new Error(info.comment || rating.comment || submissions.comment || "Codeforces rejected the request."),{status:404}); const user=info.result[0]; const profile=normalizeCodeforces(user,rating.result,submissions.result); const tags:any={}; const difficulties:any={}; submissions.result.filter((s:any)=>s.verdict==="OK").forEach((s:any)=>{(s.problem.tags||[]).forEach((tag:string)=>tags[tag]=(tags[tag]||0)+1); const key=s.problem.rating ? String(s.problem.rating) : "Unrated"; difficulties[key]=(difficulties[key]||0)+1;}); return NextResponse.json({profile,raw:{user,rating:rating.result,submissions:submissions.result},analytics:{tags:Object.entries(tags).sort((a:any,b:any)=>b[1]-a[1]).slice(0,12),difficulties:Object.entries(difficulties).sort((a:any,b:any)=>a[0]==="Unrated"?1:b[0]==="Unrated"?-1:Number(a[0])-Number(b[0])),recentSubmissions:submissions.result.slice(0,20)},source:"Codeforces API",documentation:"https://codeforces.com/apiHelp",limitations:"Solved-problem and distribution metrics use the latest 1,000 public submissions returned by Codeforces.",fetchedAt:new Date().toISOString(),durationMs:Date.now()-start}); }
  return NextResponse.json({error:"A dedicated public profile integration is not enabled for this platform."},{status:501});
 } catch(error:any) { const status=error.status || 503; return NextResponse.json({error:status===429?"This source is rate limited. Try again when its retry window has elapsed.":error.message || "The source could not be reached right now.",rateLimited:status===429,retryAfter:error.rate},{status}); } }
