import { useEffect, useMemo, useState } from 'react';
import { Link, useLocation } from 'react-router-dom';
import { Check, Database, RefreshCw, Sparkles, Target, ArrowRight, BarChart3, TrendingUp } from 'lucide-react';
import { useTrackedProfiles } from '@/hooks/use-profiles';
import type { PublicDataResult } from '@/lib/public-data';
import type { TrackedProfile } from '@/lib/integrations/registry';
import { formatNumber, numericMetrics, platformLabel, platformTone } from '@/lib/analytics/dashboard-data';
import { getIntegration } from '@/lib/integrations/registry';
import { Card, CardContent } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { TimeRangeChart } from '@/components/analytics/TimeRangeChart';

function publicToTracked(data: PublicDataResult): TrackedProfile { return { id: `explored-${data.platform}-${data.profile.username}`, platform: data.platform, handle: data.profile.username, displayName: data.profile.displayName ?? data.profile.username, avatarUrl: data.profile.avatarUrl, profileUrl: data.profile.profileUrl, lastSyncedAt: data.fetchedAt, data: { bio: data.profile.bio ?? undefined, location: data.profile.location ?? undefined, joinedAt: data.profile.joinedAt ?? undefined, metrics: data.metrics.map((m) => ({ key: m.label.toLowerCase().replace(/[^a-z0-9]+/g, '_'), label: m.label, value: m.value })), activity: data.activity.map((item) => ({ date: item.timestamp.slice(0, 10), count: 1 })), breakdowns: (data.breakdowns ?? []).map((item) => ({ key: item.label.toLowerCase().replace(/[^a-z0-9]+/g, '_'), label: item.label, items: item.items })) } }; }

function ProfileChip({ profile, active, onClick }: { profile: TrackedProfile; active: boolean; onClick: () => void }) { const Icon = getIntegration(profile.platform).icon; const tone = platformTone(profile.platform); return <button type="button" onClick={onClick} className={`group flex items-center gap-2 rounded-2xl border px-3 py-2 text-left transition hover:-translate-y-0.5 ${active ? 'border-primary/40 bg-primary/5 shadow-sm' : 'border-border bg-background hover:border-primary/30'}`}><span className={`flex h-9 w-9 items-center justify-center rounded-xl ${tone.bg} ${tone.text}`}><Icon className="h-4 w-4"/></span><span className="min-w-0"><span className="block max-w-[170px] truncate text-xs font-bold">{profile.displayName || profile.handle}</span><span className="block text-[10px] text-muted-foreground">{platformLabel(profile.platform)} · @{profile.handle}</span></span>{active && <Check className="h-3.5 w-3.5 text-primary"/>}</button>; }

function Signals({ profile }: { profile: TrackedProfile }) { const tone = platformTone(profile.platform); const breakdowns = profile.data?.breakdowns ?? []; return <div className="space-y-4">{breakdowns.slice(0, 6).map((breakdown) => { const max = Math.max(...breakdown.items.map((item) => item.value), 1); return <div key={breakdown.key} className="rounded-2xl border border-border bg-background/40 p-4"><div className="flex items-center justify-between"><p className="text-xs font-bold">{breakdown.label}</p><span className="text-[10px] text-muted-foreground">{breakdown.items.length} signals</span></div><div className="mt-4 space-y-3">{breakdown.items.slice(0, 6).map((item) => <div key={item.label}><div className="flex items-center justify-between gap-3 text-xs"><span className="truncate text-muted-foreground">{item.label}</span><strong>{formatNumber(item.value)}</strong></div><div className="mt-1.5 h-1.5 rounded-full bg-muted"><div className="h-full rounded-full" style={{ width: `${Math.max(4, item.value / max * 100)}%`, background: tone.chart }}/></div></div>)}</div></div>; })}{!breakdowns.length && <div className="rounded-2xl border border-dashed p-6 text-center text-xs text-muted-foreground">No grouped signals were returned by this platform.</div>}</div>; }

export function AnalyzeView() {
  const location = useLocation();
  const { data: connected = [], isLoading, refetch } = useTrackedProfiles();
  const explored = (location.state as { exploreProfile?: PublicDataResult } | null)?.exploreProfile;
  const exploredProfile = useMemo(() => explored ? publicToTracked(explored) : null, [explored]);
  const profiles = useMemo(() => exploredProfile ? [...connected, exploredProfile] : connected, [connected, exploredProfile]);
  const [selectedIds, setSelectedIds] = useState<string[]>([]);
  useEffect(() => { if (exploredProfile) setSelectedIds([exploredProfile.id]); else if (!selectedIds.length && connected.length) setSelectedIds([connected[0].id]); }, [connected, exploredProfile, selectedIds.length]);
  const selected = profiles.filter((profile) => selectedIds.includes(profile.id));
  const profile = selected[0];
  const activity = useMemo(() => { const map = new Map<string, number>(); selected.forEach((item) => (item.data?.activity ?? []).forEach((point) => map.set(point.date, (map.get(point.date) ?? 0) + point.count))); return Array.from(map, ([date, count]) => ({ date, count })).sort((a, b) => a.date.localeCompare(b.date)); }, [selected]);
  const toggle = (id: string) => setSelectedIds((current) => current.includes(id) ? current.filter((item) => item !== id) : [...current, id]);
  if (isLoading) return <div className="p-6"><div className="mx-auto max-w-7xl animate-pulse space-y-5"><div className="h-24 rounded-3xl bg-muted"/><div className="h-80 rounded-3xl bg-muted"/></div></div>;

  return <div className="relative min-h-full overflow-hidden"><div className="pointer-events-none absolute left-0 top-0 h-96 w-96 rounded-full bg-violet-500/[0.08] blur-3xl"/><div className="relative mx-auto max-w-7xl space-y-6 p-5 sm:p-6 lg:p-8">
    <header><div className="mb-3 flex flex-wrap gap-2"><Badge variant="outline" className="border-violet-500/30 bg-violet-500/10 text-violet-600 dark:text-violet-300"><Sparkles className="mr-1.5 h-3 w-3"/>Intelligence studio</Badge><Badge variant="outline">{selected.length} selected</Badge></div><h1 className="text-3xl font-black tracking-tight sm:text-4xl">Turn real profile data into a report.</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-muted-foreground">Every source keeps its own meaning. GitHub becomes developer activity, LeetCode becomes DSA evidence, and Codeforces becomes competitive-programming evidence.</p></header>
    <Card><CardContent className="p-5 sm:p-6"><div className="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between"><div><p className="text-[11px] font-bold uppercase tracking-[0.18em] text-muted-foreground">01 · Sources</p><p className="mt-1 text-sm font-semibold">Select one for a deep report or several for a combined view.</p></div><div className="flex gap-2"><Button size="sm" variant="outline" onClick={() => setSelectedIds([])}>Clear</Button><Button size="sm" variant="outline" onClick={() => void refetch()} className="gap-2"><RefreshCw className="h-3.5 w-3.5"/>Refresh</Button></div></div><div className="mt-4 flex flex-wrap gap-2">{profiles.length ? profiles.map((item) => <ProfileChip key={item.id} profile={item} active={selectedIds.includes(item.id)} onClick={() => toggle(item.id)}/>) : <div className="w-full rounded-2xl border border-dashed p-8 text-center"><Database className="mx-auto h-7 w-7 text-muted-foreground/40"/><p className="mt-2 text-sm font-semibold">Connect or explore a profile first.</p><Link to="/dashboard/integrations"><Button size="sm" className="mt-3">Open integrations <ArrowRight className="ml-1 h-3.5 w-3.5"/></Button></Link></div>}</div></CardContent></Card>
    {!profile ? <Card className="border-dashed"><CardContent className="p-14 text-center"><BarChart3 className="mx-auto h-10 w-10 text-muted-foreground/40"/><h2 className="mt-4 text-xl font-bold">Choose at least one profile</h2><p className="mx-auto mt-1 max-w-lg text-sm text-muted-foreground">Your selection controls the analysis below.</p></CardContent></Card> : selected.length === 1 ? <>
      <section className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-[11px] font-bold uppercase tracking-[0.18em] text-primary">02 · Individual analysis</p><h2 className="mt-1 text-3xl font-black">{profile.displayName || profile.handle}</h2><p className="text-sm text-muted-foreground">{platformLabel(profile.platform)} · @{profile.handle}</p></div><Link to={`/dashboard/profile/${profile.id}`}><Button variant="outline" size="sm">Open profile <ArrowRight className="ml-1 h-3.5 w-3.5"/></Button></Link></section>
      <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{numericMetrics(profile).slice(0, 12).map((metric, index) => <Card key={metric.key} className="group overflow-hidden transition hover:-translate-y-1 hover:shadow-lg"><CardContent className="p-5"><div className="mb-4 h-1 w-12 rounded-full" style={{ background: platformTone(profile.platform).chart }}/><p className="text-xs text-muted-foreground">{metric.label}</p><p className="mt-1 text-3xl font-black">{formatNumber(metric.value)}</p><p className="mt-1 text-[10px] font-semibold text-emerald-500">Real returned metric</p><span className="sr-only">Metric {index + 1}</span></CardContent></Card>)}</div>
      <section className="grid gap-5 xl:grid-cols-[1.5fr_1fr]"><TimeRangeChart points={activity} tone={platformTone(profile.platform).chart} title={`${platformLabel(profile.platform)} activity`} subtitle="Use 7 days, 30 days, 1 year, or all available history. 30 days is the default."/><Card><CardContent className="p-5 sm:p-6"><div className="flex items-center gap-2"><Target className="h-4 w-4 text-primary"/><h3 className="font-bold">Profile signals</h3></div><p className="mt-1 text-xs text-muted-foreground">The evidence behind this profile, grouped by the source.</p><div className="mt-5"><Signals profile={profile}/></div></CardContent></Card></section>
    </> : <>
      <section><p className="text-[11px] font-bold uppercase tracking-[0.18em] text-primary">02 · Combined analysis</p><h2 className="mt-1 text-3xl font-black">Your cross-platform developer picture</h2><p className="mt-1 max-w-3xl text-sm text-muted-foreground">Different platforms measure different skills. APIVue keeps those signals distinct, then puts them together into one readable view.</p></section>
      <div className="grid gap-4 lg:grid-cols-3">{selected.map((item) => <Card key={item.id} className="overflow-hidden"><CardContent className="p-5"><div className="h-1.5 rounded-full" style={{ background: platformTone(item.platform).chart }}/><p className="mt-4 text-xs font-semibold text-muted-foreground">{platformLabel(item.platform)}</p><h3 className="mt-1 truncate text-xl font-black">{item.displayName || item.handle}</h3><p className="font-mono text-xs text-muted-foreground">@{item.handle}</p><div className="mt-4 grid grid-cols-2 gap-2">{numericMetrics(item).slice(0, 4).map((metric) => <div key={metric.key} className="rounded-2xl bg-muted/40 p-3"><p className="truncate text-[10px] text-muted-foreground">{metric.label}</p><p className="mt-1 text-xl font-black">{formatNumber(metric.value)}</p></div>)}</div></CardContent></Card>)}</div>
      <TimeRangeChart points={activity} tone="hsl(var(--primary))" title="Combined activity" subtitle="All selected sources, normalized by date. Use the same four time ranges to inspect the available evidence."/>
      <Card><CardContent className="p-5 sm:p-6"><div className="flex items-center gap-2"><TrendingUp className="h-4 w-4 text-primary"/><h3 className="font-bold">Cross-platform signals</h3></div><div className="mt-5 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{selected.map((item) => <div key={item.id} className="rounded-2xl border border-border p-4"><p className="text-xs font-bold">{platformLabel(item.platform)}</p><div className="mt-3"><Signals profile={item}/></div></div>)}</div></CardContent></Card>
    </>}
  </div></div>;
}
