import { useEffect, useMemo, useState } from 'react';
import { Link, useLocation } from 'react-router-dom';
import { Area, AreaChart, CartesianGrid, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { Activity, ArrowRight, BarChart3, Check, Database, RefreshCw, Sparkles, Target, TrendingUp } from 'lucide-react';
import { useTrackedProfiles } from '@/hooks/use-profiles';
import type { PublicDataResult } from '@/lib/public-data';
import type { TrackedProfile } from '@/lib/integrations/registry';
import { formatNumber, numericMetrics, platformLabel, platformTone } from '@/lib/analytics/dashboard-data';
import { getIntegration } from '@/lib/integrations/registry';
import { Card, CardContent } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';

function publicToTracked(data: PublicDataResult): TrackedProfile { return { id: `explored-${data.platform}-${data.profile.username}`, platform: data.platform, handle: data.profile.username, displayName: data.profile.displayName ?? data.profile.username, avatarUrl: data.profile.avatarUrl, profileUrl: data.profile.profileUrl, lastSyncedAt: data.fetchedAt, data: { bio: data.profile.bio ?? undefined, location: data.profile.location ?? undefined, joinedAt: data.profile.joinedAt ?? undefined, metrics: data.metrics.map((m) => ({ key: m.label.toLowerCase().replace(/[^a-z0-9]+/g, '_'), label: m.label, value: m.value })), activity: data.activity.map((item) => ({ date: item.timestamp.slice(0, 10), count: 1 })), breakdowns: (data.breakdowns ?? []).map((item) => ({ key: item.label, label: item.label, items: item.items })) } }; }
function ProfileChip({ profile, active, onClick }: { profile: TrackedProfile; active: boolean; onClick: () => void }) { const Icon = getIntegration(profile.platform).icon; const tone = platformTone(profile.platform); return <button type="button" onClick={onClick} className={`flex items-center gap-2 rounded-xl border px-3 py-2 text-left transition hover:-translate-y-0.5 ${active ? `border-primary bg-primary/5 shadow-sm` : 'border-border bg-background hover:border-primary/30'}`}><span className={`flex h-8 w-8 items-center justify-center rounded-lg ${tone.bg} ${tone.text}`}><Icon className="h-4 w-4"/></span><span className="min-w-0"><span className="block max-w-[170px] truncate text-xs font-semibold">{profile.displayName || profile.handle}</span><span className="block text-[10px] text-muted-foreground">{platformLabel(profile.platform)} · @{profile.handle}</span></span>{active && <Check className="h-3.5 w-3.5 text-primary"/>}</button>; }

export function AnalyzeView() {
  const location = useLocation(); const { data: connected = [], isLoading, refetch } = useTrackedProfiles(); const explored = (location.state as { exploreProfile?: PublicDataResult } | null)?.exploreProfile; const exploredProfile = useMemo(() => explored ? publicToTracked(explored) : null, [explored]); const profiles = useMemo(() => exploredProfile ? [...connected, exploredProfile] : connected, [connected, exploredProfile]); const [selectedIds, setSelectedIds] = useState<string[]>([]);
  useEffect(() => { if (exploredProfile) setSelectedIds([exploredProfile.id]); else if (!selectedIds.length && connected.length) setSelectedIds([connected[0].id]); /* eslint-disable-next-line react-hooks/exhaustive-deps */ }, [exploredProfile?.id, connected.length]);
  const selected = profiles.filter((p) => selectedIds.includes(p.id)); const profile = selected[0]; const tone = platformTone(profile?.platform ?? 'github'); const activity = useMemo(() => { const map = new Map<string, number>(); selected.forEach((p) => (p.data?.activity ?? []).forEach((a) => map.set(a.date, (map.get(a.date) ?? 0) + a.count))); return Array.from(map, ([date, count]) => ({ date, count })).sort((a,b)=>a.date.localeCompare(b.date)); }, [selected]);
  if (isLoading) return <div className="p-6"><div className="mx-auto max-w-7xl animate-pulse space-y-5"><div className="h-32 rounded-2xl bg-muted"/><div className="h-72 rounded-2xl bg-muted"/></div></div>;
  const toggle = (id: string) => setSelectedIds((current) => current.includes(id) ? current.filter((x) => x !== id) : [...current, id]);
  return <div className="relative min-h-full overflow-hidden"><div className="pointer-events-none absolute left-0 top-0 h-96 w-96 rounded-full bg-violet-500/[0.07] blur-3xl"/><div className="relative mx-auto max-w-7xl space-y-6 p-5 sm:p-6 lg:p-8">
    <header><div className="mb-3 flex flex-wrap gap-2"><Badge variant="outline" className="border-violet-500/30 bg-violet-500/10 text-violet-600 dark:text-violet-300"><Sparkles className="mr-1.5 h-3 w-3"/>Intelligence studio</Badge><Badge variant="outline">{selected.length} selected</Badge></div><h1 className="text-3xl font-bold tracking-tight sm:text-4xl">Turn profile data into a useful report.</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-muted-foreground">One source gives you a deep platform report. Multiple sources become a cross-platform intelligence view. Missing data stays missing — APIVue never invents it.</p></header>
    <Card><CardContent className="p-5"><div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-xs font-semibold uppercase tracking-wider text-muted-foreground">01 · Sources</p><p className="mt-1 text-sm font-medium">Choose what you want to analyze</p></div><div className="flex gap-2"><Button size="sm" variant="outline" onClick={()=>setSelectedIds([])}>Clear</Button><Button size="sm" variant="outline" onClick={()=>void refetch()} className="gap-2"><RefreshCw className="h-3.5 w-3.5"/>Refresh</Button></div></div><div className="mt-4 flex flex-wrap gap-2">{profiles.length ? profiles.map((p)=><ProfileChip key={p.id} profile={p} active={selectedIds.includes(p.id)} onClick={()=>toggle(p.id)}/>) : <div className="w-full rounded-xl border border-dashed p-7 text-center"><Database className="mx-auto h-7 w-7 text-muted-foreground/40"/><p className="mt-2 text-sm font-medium">Connect or explore a profile first.</p><Link to="/dashboard/integrations"><Button size="sm" className="mt-3">Open integrations <ArrowRight className="ml-1 h-3.5 w-3.5"/></Button></Link></div>}</div></CardContent></Card>
    {!profile ? <Card className="border-dashed"><CardContent className="p-12 text-center"><BarChart3 className="mx-auto h-10 w-10 text-muted-foreground/40"/><h2 className="mt-4 text-lg font-semibold">Choose at least one profile</h2><p className="mx-auto mt-1 max-w-lg text-sm text-muted-foreground">Your selected platform becomes a complete analysis report instead of a generic empty chart.</p></CardContent></Card> : selected.length === 1 ? <>
      <section className="flex items-end justify-between gap-3"><div><p className="text-xs font-semibold uppercase tracking-wider text-primary">02 · Individual report</p><h2 className="mt-1 text-2xl font-bold">{profile.displayName || profile.handle}</h2><p className="text-sm text-muted-foreground">{platformLabel(profile.platform)} · @{profile.handle}</p></div><Link to={`/dashboard/profile/${profile.id}`}><Button variant="outline" size="sm">Open full profile <ArrowRight className="ml-1 h-3.5 w-3.5"/></Button></Link></section>
      <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{numericMetrics(profile).slice(0,8).map((m)=><Card key={m.key} className="overflow-hidden"><CardContent className="p-5"><div className={`mb-3 h-1 w-12 rounded-full`} style={{ background: tone.chart }}/><p className="text-xs text-muted-foreground">{m.label}</p><p className="mt-1 text-3xl font-bold">{formatNumber(m.value)}</p><p className="mt-1 text-[10px] text-emerald-500">Real returned metric</p></CardContent></Card>)}</div>
      <section className="grid gap-5 lg:grid-cols-[1.5fr_1fr]"><Card><CardContent className="p-5 sm:p-6"><div className="flex items-center justify-between"><div><p className="text-xs font-semibold uppercase tracking-wider text-muted-foreground">03 · Activity</p><h3 className="mt-1 font-semibold">Activity over time</h3></div><Activity className="h-4 w-4 text-muted-foreground"/></div><div className="mt-5 h-72">{activity.length > 1 ? <ResponsiveContainer width="100%" height="100%"><AreaChart data={activity}><defs><linearGradient id="analysisActivity" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor={tone.chart} stopOpacity={.3}/><stop offset="100%" stopColor={tone.chart} stopOpacity={0}/></linearGradient></defs><CartesianGrid strokeDasharray="3 3" stroke="hsl(var(--border))" vertical={false}/><XAxis dataKey="date" tick={{fontSize:10}} tickFormatter={(v)=>String(v).slice(5)}/><YAxis allowDecimals={false} tick={{fontSize:10}}/><Tooltip contentStyle={{borderRadius:12,border:'1px solid hsl(var(--border))',background:'hsl(var(--card))'}}/><Area type="monotone" dataKey="count" stroke={tone.chart} fill="url(#analysisActivity)" strokeWidth={2.5}/></AreaChart></ResponsiveContainer> : <div className="flex h-full items-center justify-center rounded-xl border border-dashed text-sm text-muted-foreground">No dated activity returned by this source.</div>}</div></CardContent></Card><Card><CardContent className="p-5 sm:p-6"><div className="flex items-center gap-2"><Target className="h-4 w-4 text-primary"/><h3 className="font-semibold">Profile signals</h3></div><div className="mt-4 space-y-3">{(profile.data?.breakdowns ?? []).slice(0,5).map((b)=><div key={b.key} className="rounded-xl border border-border/70 p-3"><p className="text-xs font-semibold">{b.label}</p>{b.items.slice(0,5).map((item)=><div key={item.label} className="mt-2 flex items-center justify-between gap-3 text-xs"><span className="truncate text-muted-foreground">{item.label}</span><span className="font-semibold">{formatNumber(item.value)}</span></div>)}</div>)}{!profile.data?.breakdowns?.length && <p className="rounded-xl border border-dashed p-5 text-center text-xs text-muted-foreground">This platform did not return grouped signals.</p>}</div></CardContent></Card></section>
    </> : <>
      <section><p className="text-xs font-semibold uppercase tracking-wider text-primary">02 · Combined report</p><h2 className="mt-1 text-2xl font-bold">Your cross-platform developer picture</h2><p className="mt-1 text-sm text-muted-foreground">Each platform keeps its own meaning. APIVue combines the evidence without pretending that a GitHub repository is equivalent to a contest rating.</p></section>
      <div className="grid gap-4 lg:grid-cols-3">{selected.map((p)=><Card key={p.id} className="overflow-hidden"><CardContent className="p-5"><div className={`mb-4 h-1.5 rounded-full`} style={{background: platformTone(p.platform).chart}}/><p className="text-xs text-muted-foreground">{platformLabel(p.platform)}</p><h3 className="mt-1 truncate text-lg font-bold">{p.displayName || p.handle}</h3><p className="font-mono text-xs text-muted-foreground">@{p.handle}</p><div className="mt-4 grid grid-cols-2 gap-3">{numericMetrics(p).slice(0,4).map((m)=><div key={m.key} className="rounded-xl bg-muted/40 p-3"><p className="text-[10px] text-muted-foreground">{m.label}</p><p className="mt-1 text-xl font-bold">{formatNumber(m.value)}</p></div>)}</div></CardContent></Card>)}</div>
      <Card><CardContent className="p-5 sm:p-6"><div className="flex items-center gap-2"><TrendingUp className="h-4 w-4 text-primary"/><div><p className="text-xs font-semibold uppercase tracking-wider text-muted-foreground">03 · Activity</p><h3 className="mt-1 font-semibold">Combined returned activity</h3></div></div><div className="mt-5 h-72">{activity.length > 1 ? <ResponsiveContainer width="100%" height="100%"><LineChart data={activity}><CartesianGrid strokeDasharray="3 3" stroke="hsl(var(--border))" vertical={false}/><XAxis dataKey="date" tick={{fontSize:10}} tickFormatter={(v)=>String(v).slice(5)}/><YAxis allowDecimals={false} tick={{fontSize:10}}/><Tooltip contentStyle={{borderRadius:12,border:'1px solid hsl(var(--border))',background:'hsl(var(--card))'}}/><Line type="monotone" dataKey="count" stroke="hsl(var(--primary))" strokeWidth={2.5} dot={false}/></LineChart></ResponsiveContainer> : <div className="flex h-full items-center justify-center rounded-xl border border-dashed text-sm text-muted-foreground">Selected sources did not return enough dated activity for a combined chart.</div>}</div></CardContent></Card>
    </>}
  </div></div>;
}
