import { describe, expect, it } from 'vitest';
import { calculateGoalProgress, calculateAllGoalsProgress } from '@/lib/analytics/goals';
import { currentGoalStreak, resolveGoalValue } from '@/lib/analytics/goal-tracking';
import type { Goal } from '@/hooks/use-goals';
import type { ProfileSnapshot, TrackedProfile } from '@/lib/integrations/registry';

const baseGoal = (overrides: Partial<Goal> = {}): Goal => ({ id:'g1', title:'Test goal', description:null, category:null, target_value:100, current_value:0, unit:'items', start_date:null, target_date:null, status:'active', metadata:null, created_at:'2026-01-01T00:00:00Z', ...overrides });
const profile = (metrics: Array<{key:string;label:string;value:number;format?:string}>, activity: Array<{date:string;count:number}> = []): TrackedProfile => ({ id:'p1', platform:'codeforces', handle:'tester', display_name:'Tester', pinned:true, last_synced_at:new Date().toISOString(), sync_error:null, data:{ metrics, activity } });
const snapshots: ProfileSnapshot[] = [{id:'s1',profile_id:'p1',captured_at:'2026-09-01T00:00:00Z',metrics:{solves:10,rating:1200}},{id:'s2',profile_id:'p1',captured_at:'2026-09-02T00:00:00Z',metrics:{solves:15,rating:1300}}];

describe('Goals analytics',()=>{
  it('keeps manual goals working when no tracker is configured',()=>{const goal=baseGoal({current_value:25});expect(calculateGoalProgress(goal,[],[]).currentValue).toBe(25);});
  it('derives a goal from a selected live profile metric',()=>{const p=profile([{key:'solves',label:'Problems Solved',value:42}]);const goal=baseGoal({metadata:{tracking:{mode:'metric',period:'lifetime',profileId:'p1',metricKey:'solves',baseline:20}}});const result=calculateGoalProgress(goal,[p],snapshots);expect(result.currentValue).toBe(42);expect(result.progressPercentage).toBe(42);});
  it('supports daily activity goals that reset to the current local day',()=>{const today=new Date();const key=`${today.getFullYear()}-${String(today.getMonth()+1).padStart(2,'0')}-${String(today.getDate()).padStart(2,'0')}`;const p=profile([],[{date:key,count:7},{date:'2026-01-01',count:99}]);const goal=baseGoal({metadata:{tracking:{mode:'activity',period:'daily'}}});expect(resolveGoalValue(goal,[p],[])).toBe(7);});
  it('calculates a current streak from consecutive real activity days',()=>{const d=new Date();const dates=[];for(let i=2;i>=0;i--){const x=new Date(d);x.setDate(d.getDate()-i);dates.push(`${x.getFullYear()}-${String(x.getMonth()+1).padStart(2,'0')}-${String(x.getDate()).padStart(2,'0')}`);}const p=profile([],[{date:dates[0],count:1},{date:dates[1],count:2},{date:dates[2],count:3}]);expect(currentGoalStreak([p])).toBe(3);});
  it('auto-infers a metric for legacy goals when title matches real data',()=>{const p=profile([{key:'solves',label:'Problems Solved',value:88}]);const goal=baseGoal({title:'Solve 100 problems',unit:'problems'});const result=calculateGoalProgress(goal,[p],snapshots);expect(result.currentValue).toBe(88);});
  it('never produces progress above 100%',()=>{const p=profile([{key:'solves',label:'Problems Solved',value:150}]);const goal=baseGoal({metadata:{tracking:{mode:'metric',period:'lifetime',profileId:'p1',metricKey:'solves'}}});expect(calculateGoalProgress(goal,[p],[]).progressPercentage).toBe(100);});
  it('calculates every goal independently',()=>{const p=profile([{key:'solves',label:'Problems Solved',value:20},{key:'rating',label:'Rating',value:1500}]);const goals=[baseGoal({id:'a',title:'Problems',metadata:{tracking:{mode:'metric',period:'lifetime',profileId:'p1',metricKey:'solves'}}}),baseGoal({id:'b',title:'Rating',metadata:{tracking:{mode:'metric',period:'lifetime',profileId:'p1',metricKey:'rating'}},target_value:2000})];const all=calculateAllGoalsProgress(goals,[p],[]);expect(all.map(x=>x.currentValue)).toEqual([20,1500]);});
});
