import { Award, BarChart3, CheckCircle2, Code2, ExternalLink, Medal, RefreshCw, Sparkles, Star, Trophy } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import type { ProfileSnapshot, TrackedProfile } from '@/lib/integrations/registry';
import { ProfileAvatar } from '@/components/apivue/ProfileBits';
import { ActivityHeatmap, HistoryChart, type ActivityPoint } from '@/components/apivue/ProfileAnalyticsKit';
import './community-profile.css';
import './profile-analytics.css';
const num=(v:unknown)=>{const n=Number(v);return Number.isFinite(n)?n:0};const fmt=(v:unknown)=>num(v).toLocaleString();const metric=(d:TrackedProfile['data'],label:string)=>d?.metrics?.find((m)=>m.label.toLowerCase()===label.toLowerCase())?.value;
function Stat({label,value,Icon}:{label:string;value:number;Icon:typeof Code2}){return <div className="com-stat"><div><span>{label}</span><Icon/></div><strong>{Math.round(value).toLocaleString()}</strong><small>Real public metric</small></div>}
function Bars({items}:{items:{label:string;value:number}[]}){const max=Math.max(...items.map((x)=>x.value),1);return <div className="com-bars">{items.slice(0,10).map((x)=><div className="com-bar" key={x.label}><div><span>{x.label}</span><b>{fmt(x.value)}</b></div><div className="com-track"><i style={{width:`${Math.max(3,x.value/max*100)}%`}}/></div></div>)}{!items.length&&<p className="com-muted">No breakdown returned by the provider yet.</p>}</div>}
export function CommunityProfileView({profile,snapshots,refreshing,onRefresh}:{profile:TrackedProfile;snapshots:ProfileSnapshot[];refreshing:boolean;onRefresh:()=>void}){const codewars=profile.platform==='codewars';const name=codewars?'Codewars':'Stack Overflow';const data=profile.data;const metrics=codewars?{a:num(metric(data,'Honor')),b:num(metric(data,'Overall score')),c:num(metric(data,'Katas completed')),d:num(metric(data,'Katas authored'))}:{a:num(metric(data,'Reputation')),b:num(metric(data,'Answers')),c:num(metric(data,'Questions')),d:num(metric(data,'Profile views'))};const breakdowns=data?.breakdowns??[];const first=(breakdowns[0]?.items??[]) as {label:string;value:number}[];const badgeItems=codewars?[]:[['Gold badges',num(metric(data,'Gold badges'))],['Silver badges',num(metric(data,'Silver badges'))],['Bronze badges',num(metric(data,'Bronze badges'))]].map(([label,value])=>({label:String(label),value:num(value)}));const activity=(data?.activity??[]) as ActivityPoint[];const history=snapshots.slice().sort((a,b)=>a.captured_at.localeCompare(b.captured_at)).map(s=>({date:s.captured_at.slice(0,10),value:num(s.metrics[codewars?'honor':'reputation']??s.metrics[codewars?'overall_score':'reputation']),label:`${name} snapshot`}));const avatarProfile={...profile,avatarUrl:profile.avatarUrl??data?.avatarUrl??null,displayName:profile.displayName??data?.displayName??profile.handle};return <div className="com-page"><header className="com-top"><div className="com-brand"><b>A</b><span>APIVue · {name} Profile</span></div><Badge variant="outline" className="com-live"><span/> LIVE DATA</Badge></header>
<section className="com-profile"><div className="com-glow"/><div className="com-profile-row"><div className="com-avatar-wrap"><div className="com-ring"/><ProfileAvatar profile={avatarProfile} size="xl"/></div><div className="com-info"><div className="com-name"><h1>{profile.displayName||profile.handle}</h1><span><Sparkles/> {String(metric(data,codewars?'Overall rank':'Reputation')??'Public profile')}</span></div><div className="com-handle">@{profile.handle}</div><p>{data?.bio||`Real ${name} analytics collected by APIVue.`}</p><div className="com-meta"><span><Code2/>{name}</span>{data?.location&&<span>📍 {data.location}</span>}{data?.joinedAt&&<span>📅 Joined {new Date(data.joinedAt).toLocaleDateString()}</span>}</div></div><div className="com-actions"><a href={profile.profileUrl??profile.profile_url} target="_blank" rel="noreferrer noopener"><Button variant="outline"><ExternalLink/>View profile</Button></a><Button onClick={onRefresh} disabled={refreshing}><RefreshCw className={refreshing?'animate-spin':''}/>Refresh</Button></div></div></section>
<div className="com-stats"><Stat label={codewars?'Honor':'Reputation'} value={metrics.a} Icon={codewars?Award:Star}/><Stat label={codewars?'Overall score':'Answers'} value={metrics.b} Icon={BarChart3}/><Stat label={codewars?'Katas completed':'Questions'} value={metrics.c} Icon={codewars?Code2:CheckCircle2}/><Stat label={codewars?'Katas authored':'Profile views'} value={metrics.d} Icon={Trophy}/></div>
{codewars&&<ActivityHeatmap activity={activity} title="Kata completion activity"/>}<section className="com-card"><div className="com-head"><div><h2><BarChart3/>{codewars?'Honor progression':'Reputation progression'}</h2><p>{history.length>1?`Real APIVue snapshot history · ${history.length} snapshots`:'Your real history will appear here as APIVue collects snapshots.'}</p></div><span className="com-pill"><Sparkles/> Live analytics</span></div><HistoryChart points={history} valueLabel={codewars?'Honor':'Reputation'}/></section>
<div className="com-grid2"><section className="com-card"><div className="com-card-title"><Code2/>{codewars?'Language scores':'Top answer tags'}</div><Bars items={first}/></section><section className="com-card"><div className="com-card-title"><Medal/>{codewars?'Rank analytics':'Badge distribution'}</div>{codewars?<div className="com-rank"><div className="com-rank-number">{String(metric(data,'Overall rank')??'Unranked')}</div><div><b>{fmt(metrics.b)} overall score</b><span>Leaderboard position: {fmt(metric(data,'Leaderboard position')??0)}</span><span>{fmt(metrics.c)} kata completed · {fmt(metrics.d)} authored</span></div></div>:<Bars items={badgeItems}/>}</section></div>
<section className="com-card"><div className="com-card-title"><Trophy/>Achievements</div><div className="com-achievements">{(codewars?[metrics.c>=10&&'🎯 10+ kata',metrics.c>=50&&'🔥 50+ kata',metrics.a>=100&&'⭐ 100+ honor',metrics.d>=5&&'✍️ 5+ authored']:[metrics.a>=100&&'⭐ 100+ reputation',metrics.b>=10&&'💬 10+ answers',metrics.c>=10&&'❓ 10+ questions',num(metric(data,'Gold badges'))>0&&'🏆 Gold badge']).filter(Boolean).map(x=><span key={String(x)}>{x}</span>)}<span>📊 {activity.length?'Live':'Public'} analytics</span></div></section>
<section className="com-insight"><Sparkles/><div><b>APIVue Insight</b><p>{codewars?<>You have completed <strong>{fmt(metrics.c)}</strong> kata with <strong>{fmt(metrics.a)}</strong> honor and a language profile built from real Codewars rank scores.</>:<>Your profile has <strong>{fmt(metrics.a)}</strong> reputation, <strong>{fmt(metrics.b)}</strong> answers and <strong>{fmt(metrics.c)}</strong> questions. The tag distribution above is calculated from your public Stack Overflow data.</>}</p></div></section></div>}
