import { useMemo } from 'react';
import { Activity, Award, BarChart3, CheckCircle2, Code2, ExternalLink, Moon, RefreshCw, Sparkles, Sun, Trophy } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { useTheme } from '@/lib/theme-context';
import { ProfileAvatar } from '@/components/apivue/ProfileBits';
import { ActivityHeatmap, HistoryChart, type ActivityPoint, type HistoryPoint } from '@/components/apivue/ProfileAnalyticsKit';
import type { ProfileSnapshot, TrackedProfile } from '@/lib/integrations/registry';
import './competitive-profile.css';
import './profile-analytics.css';
const n=(v:unknown)=>{const x=Number(v);return Number.isFinite(x)?x:0};const fmt=(v:unknown)=>n(v).toLocaleString();const metric=(d:TrackedProfile['data'],label:string)=>d?.metrics?.find((m)=>m.label.toLowerCase()===label.toLowerCase())?.value;
function Stat({label,value,Icon}:{label:string;value:number;Icon:typeof Code2}){return <div className="cp-stat"><div className="cp-stat-head"><span>{label}</span><Icon/></div><strong>{label==='Acceptance rate'?`${value.toFixed(0)}%`:Math.round(value).toLocaleString()}</strong><small>Real public metric</small></div>}
function Bars({items}:{items:{label:string;value:number}[]}){const max=Math.max(...items.map((x)=>x.value),1);return <div className="cp-bars">{items.slice(0,10).map((x)=><div className="cp-bar" key={x.label}><span>{x.label}</span><div><i style={{width:`${Math.max(3,x.value/max*100)}%`}}/></div><b>{fmt(x.value)}</b></div>)}{!items.length&&<p className="cp-muted">No breakdown returned yet.</p>}</div>}
export function CompetitiveProfileView({profile,snapshots,refreshing,onRefresh}:{profile:TrackedProfile;snapshots:ProfileSnapshot[];refreshing:boolean;onRefresh:()=>void}){const{theme,setTheme}=useTheme();const data=profile.data;const leetcode=profile.platform==='leetcode';const name=leetcode?'LeetCode':'Codeforces';const solved=n(metric(data,'Problems solved')),easy=n(metric(data,'Easy solved')),medium=n(metric(data,'Medium solved')),hard=n(metric(data,'Hard solved')),rating=n(metric(data,leetcode?'Contest rating':'Current rating')),peak=n(metric(data,leetcode?'Contest rating':'Max rating')),contests=n(metric(data,leetcode?'Contests attended':'Rated contests')),acceptance=n(metric(data,'Acceptance rate')),ranking=metric(data,leetcode?'Global ranking':'Current rank');const activity=(data?.activity??[]) as ActivityPoint[];const ratings=(data?.ratingHistory??[]) as HistoryPoint[];const breakdowns=data?.breakdowns??[];const langs=breakdowns.find((x)=>/language/i.test(x.label))?.items??[];const tags=breakdowns.find((x)=>/topic|tag/i.test(x.label))?.items??[];const verdicts=breakdowns.find((x)=>/verdict/i.test(x.label))?.items??[];const submissions=activity.reduce((sum,item)=>sum+item.count,0);const difficulty=[['Easy',easy],['Medium',medium],['Hard',hard]] as const;const maxDifficulty=Math.max(...difficulty.map(([,value])=>value),1);const chartPoints=ratings.map((point)=>({...point,value:n(point.value),label:point.label??(leetcode?'LeetCode contest':'Codeforces contest')}));const avatarProfile={...profile,avatarUrl:profile.avatarUrl??data?.avatarUrl??null,displayName:profile.displayName??data?.displayName??profile.handle};return <div className="cp-page" style={{'--cp-accent':leetcode?'#ffc01e':'#1f8acb'} as React.CSSProperties}>
<header className="cp-topbar"><div className="cp-brand"><b>A</b><span>APIVue · {name} Profile</span></div><div className="cp-actions"><Badge variant="outline" className="cp-live"><span/> LIVE DATA</Badge><button type="button" className="cp-theme" onClick={()=>setTheme(theme==='dark'?'light':'dark')}>{theme==='dark'?<Sun/>:<Moon/>}<span>{theme==='dark'?'Light':'Dark'}</span></button></div></header>
<section className="cp-profile"><div className="cp-glow"/><div className="cp-profile-top"><div className="cp-avatar-wrap"><div className="cp-ring"/><ProfileAvatar profile={avatarProfile} size="xl"/></div><div className="cp-info"><div className="cp-name"><h1>{profile.displayName||profile.handle}</h1><span className="cp-rank"><Sparkles/>{String(ranking??'Competitive profile')}</span></div><div className="cp-handle">@{profile.handle}</div><p>{data?.bio||`${name} analytics calculated from the latest public profile response.`}</p><div className="cp-meta"><span className="cp-platform"><Code2/>{name}</span>{data?.location&&<span>📍 {data.location}</span>}{data?.joinedAt&&<span>📅 Joined {new Date(data.joinedAt).toLocaleDateString()}</span>}<span>{fmt(contests)} contests</span></div></div><div className="cp-profile-actions"><a href={profile.profileUrl??profile.profile_url} target="_blank" rel="noreferrer noopener"><Button variant="outline"><ExternalLink/>View profile</Button></a><Button onClick={onRefresh} disabled={refreshing}><RefreshCw className={refreshing?'animate-spin':''}/>Refresh</Button></div></div></section>
<div className="cp-stats"><Stat label={leetcode?'Problems solved':'Current rating'} value={leetcode?solved:rating} Icon={leetcode?Code2:Trophy}/><Stat label={leetcode?'Global ranking':'Max rating'} value={leetcode?n(metric(data,'Global ranking')):peak} Icon={Award}/><Stat label={leetcode?'Contest rating':'Problems solved'} value={leetcode?rating:solved} Icon={Trophy}/><Stat label="Acceptance rate" value={acceptance} Icon={CheckCircle2}/></div>
{leetcode&&<section className="cp-card cp-reveal"><div className="cp-head"><div><h2><BarChart3/>Difficulty breakdown</h2><p>Real solved-problem distribution returned by LeetCode</p></div><span className="cp-total-pill">{fmt(solved)} solved</span></div><div className="cp-diff-rows">{difficulty.map(([label,value])=><div className="cp-diff-row" key={label}><div><span>{label}</span><b>{fmt(value)}</b></div><div className="cp-track"><i style={{width:`${Math.min(100,value/maxDifficulty*100)}%`}}/></div></div>)}</div></section>}
<ActivityHeatmap activity={activity} title="Submission activity"/>
<section className="cp-card cp-reveal"><div className="cp-head"><div><h2><BarChart3/>{leetcode?'Contest rating':'Rating progression'}</h2><p>{ratings.length>1?`Real rating history across ${ratings.length} recorded contests`:'Waiting for real contest history from the provider'}</p></div><span className="cp-rating"><small>Current</small><strong>{fmt(rating)}</strong></span></div><HistoryChart points={chartPoints} valueLabel="Rating"/></section>
<div className="cp-two"><section className="cp-card cp-reveal"><div className="cp-card-title"><Code2/>{leetcode?'Languages used':'Problem topics'}</div><Bars items={leetcode?langs:tags}/></section><section className="cp-card cp-reveal"><div className="cp-card-title"><Activity/>{leetcode?'Strongest topics':'Verdict distribution'}</div><Bars items={leetcode?tags:verdicts}/></section></div>
<section className="cp-insight cp-reveal"><div><Sparkles/>APIVue Insight · calculated from live data</div><p>{leetcode?<>You have solved <strong>{fmt(solved)}</strong> problems, with <strong>{fmt(hard)} hard</strong> solutions and <strong>{fmt(submissions)}</strong> submission events represented in the activity calendar.</>:<>Your current rating is <strong>{fmt(rating)}</strong> with a peak of <strong>{fmt(peak)}</strong>. APIVue has collected <strong>{fmt(submissions)}</strong> recent submissions and <strong>{fmt(ratings.length)}</strong> contest ratings.</>}</p></section>
<section className="cp-card cp-reveal"><div className="cp-card-title"><Trophy/>Achievements</div><div className="cp-badges">{(leetcode?[solved>=100&&'🎯 100+ solved',solved>=500&&'🏆 500+ solved',hard>=50&&'💎 50+ hard',contests>=10&&'🚀 10+ contests']:[rating>=1200&&'⭐ 1200+ rating',rating>=1600&&'⚡ 1600+ rating',rating>=2000&&'🏆 2000+ rating',solved>=100&&'🎯 100+ solved']).filter(Boolean).map((item)=><span key={String(item)}>{item}</span>)}{!((leetcode?[solved>=100,solved>=500,hard>=50,contests>=10]:[rating>=1200,rating>=1600,rating>=2000,solved>=100]).some(Boolean))&&<p className="cp-muted">Achievements unlock automatically from real collected metrics.</p>}</div></section>
</div>}
