import { useEffect, useMemo, useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { Area, AreaChart, Bar, BarChart, CartesianGrid, Cell, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { Activity, ArrowLeft, Code2, ExternalLink, GitBranch, Globe2, Lock, MapPin, RefreshCw, ShieldCheck, Star, GitPullRequest } from 'lucide-react';
import { useProfileSnapshots, useSyncProfile, useTrackedProfiles } from '@/hooks/use-profiles';
import { getIntegration } from '@/lib/integrations/registry';
import { formatNumber, numericMetrics, platformLabel, platformTone, snapshotDelta } from '@/lib/analytics/dashboard-data';
import { Card, CardContent } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { toast } from '@/hooks/use-toast';
const tooltip={borderRadius:12,border:'1px solid hsl(var(--border))',background:'hsl(var(--card))'};
export function ProfileDetailView(){
 const {id}=useParams<{id:string}>();const {data:profiles=[],isLoading,refetch}=useTrackedProfiles();const {data:snapshots=[]}=useProfileSnapshots(id);const sync=useSyncProfile();const [refreshing,setRefreshing]=useState(false);const [liveActivity,setLiveActivity]=useState<Array<{date:string;count:number}>>([]);const [liveMeta,setLiveMeta]=useState<Record<string,unknown>|null>(null);const profile=profiles.find(p=>p.id===id);const integration=profile?getIntegration(profile.platform):null;const tone=platformTone(profile?.platform??'github');
 useEffect(()=>{if(!profile||profile.platform!=='github')return;let cancelled=false;(async()=>{try{const [u,e]=await Promise.all([fetch(`https://api.github.com/users/${encodeURIComponent(profile.handle)}`,{headers:{Accept:'application/vnd.github+json'}}),fetch(`https://api.github.com/users/${encodeURIComponent(profile.handle)}/events?per_page=100`,{headers:{Accept:'application/vnd.github+json'}})]);if(!u.ok)return;const user=await u.json() as Record<string,unknown>;const events=e.ok?await e.json() as unknown[]:[];const map=new Map<string,number>();for(const raw of events){if(!raw||typeof raw!=='object')continue;const d=typeof (raw as Record<string,unknown>).created_at==='string'?(raw as Record<string,unknown>).created_at as string:'';const day=d.slice(0,10);if(day)map.set(day,(map.get(day)??0)+1);}if(!cancelled){setLiveMeta(user);setLiveActivity(Array.from(map,([date,count])=>({date,count})).sort((a,b)=>a.date.localeCompare(b.date)));}}catch{}})();return()=>{cancelled=true;};},[profile]);
 const metrics=useMemo(()=>{if(!profile)return[];const base=numericMetrics(profile);if(profile.platform!=='github'||!liveMeta)return base;const repos=profile.data?.repositories??[];const stars=repos.reduce((s,r)=>s+Number(r.stargazers_count??r.stars??0),0);const forks=repos.reduce((s,r)=>s+Number(r.forks_count??r.forks??0),0);const replace=(key:string,label:string,value:number)=>({key,label,value,platform:'github'});return[replace('repository_total','Repositories',repos.length),replace('stars_total','Stars',stars),replace('forks_total','Forks',forks),replace('followers','Followers',Number(liveMeta.followers??0)),replace('following','Following',Number(liveMeta.following??0)),replace('public_gists','Public gists',Number(liveMeta.public_gists??0)),...base.filter(m=>!['repository_total','stars_total','forks_total','followers','following','public_gists'].includes(m.key))];},[liveMeta,profile]);
 const activity=profile?.platform==='github'&&liveActivity.length>1?liveActivity:(profile?.data?.activity??[]);const repos=profile?.data?.repositories??[];const history=useMemo(()=>{if(!profile)return[];const keys=new Set(snapshots.flatMap(s=>Object.keys(s.metrics??{})));return Array.from(keys).map(key=>({key,label:metrics.find(m=>m.key===key)?.label??key.replaceAll('_',' '),points:snapshots.map(s=>({date:s.captured_at.slice(5,10),value:Number(s.metrics[key]??0)}))}));},[metrics,profile,snapshots]);
 if(isLoading)return <div className="p-6"><div className="mx-auto max-w-7xl animate-pulse space-y-5"><div className="h-32 rounded-2xl bg-muted"/><div className="h-48 rounded-2xl bg-muted"/><div className="h-72 rounded-2xl bg-muted"/></div></div>;
 if(!profile||!integration)return <div className="p-6"><Card><CardContent className="p-10 text-center"><p className="font-semibold">Profile not found</p><p className="mt-1 text-sm text-muted-foreground">This profile is no longer tracked.</p><Link to="/dashboard/profiles"><Button className="mt-4" variant="outline"><ArrowLeft className="mr-2 h-4 w-4"/>Back to profiles</Button></Link></CardContent></Card></div>;
 const refresh=async()=>{setRefreshing(true);try{await sync.mutateAsync({platform:profile.platform,handle:profile.handle});await refetch();toast({title:'Profile refreshed',description:'Latest source data requested.'});}catch(e){toast({title:'Refresh failed',description:e instanceof Error?e.message:'Could not refresh profile.',variant:'destructive'});}finally{setRefreshing(false);}};
 return <div className="relative min-h-full overflow-hidden"><div className="pointer-events-none absolute -top-32 right-0 h-96 w-96 rounded-full bg-primary/[0.07] blur-3xl"/><div className="relative mx-auto max-w-7xl space-y-6 p-5 sm:p-6 lg:p-8">
  <Link to="/dashboard/profiles" className="inline-flex items-center gap-1.5 text-xs text-muted-foreground hover:text-foreground"><ArrowLeft className="h-3.5 w-3.5"/>Profiles</Link>
  <Card className="overflow-hidden bg-card/85"><CardContent className="p-6 sm:p-8"><div className="flex flex-col gap-6 lg:flex-row lg:items-center lg:justify-between"><div className="flex min-w-0 items-center gap-4"><div className={`flex h-20 w-20 shrink-0 items-center justify-center overflow-hidden rounded-2xl ring-1 ${tone.ring} ${tone.bg}`}>{profile.avatarUrl?<img src={profile.avatarUrl} alt="" className="h-full w-full object-cover"/>:<Code2 className={`h-8 w-8 ${tone.text}`}/>}</div><div className="min-w-0"><div className="flex flex-wrap gap-2"><Badge variant="outline" className={`${tone.bg} ${tone.text}`}>{platformLabel(profile.platform)}</Badge>{profile.data?.privateAccess&&<Badge variant="outline" className="gap-1"><ShieldCheck className="h-3 w-3"/>Verified access</Badge>}</div><h1 className="mt-2 truncate text-2xl font-bold sm:text-3xl">{profile.displayName||profile.handle}</h1><p className="font-mono text-sm text-muted-foreground">@{profile.handle}</p><div className="mt-2 flex flex-wrap gap-3 text-xs text-muted-foreground">{(liveMeta?.location as string)&&<span className="inline-flex items-center gap-1"><MapPin className="h-3 w-3"/>{String(liveMeta.location)}</span>}{(liveMeta?.created_at as string)&&<span>Joined {new Date(String(liveMeta.created_at)).toLocaleDateString()}</span>}<span>Synced {profile.lastSyncedAt?new Date(profile.lastSyncedAt).toLocaleString():'—'}</span></div>{((liveMeta?.bio as string)||profile.data?.bio)&&<p className="mt-3 max-w-2xl text-sm leading-6 text-muted-foreground">{String(liveMeta?.bio??profile.data?.bio)}</p>}</div></div><div className="flex flex-wrap gap-2">{profile.profileUrl&&<a href={profile.profileUrl} target="_blank" rel="noreferrer noopener"><Button variant="outline" className="gap-2"><ExternalLink className="h-4 w-4"/>View on {integration.name}</Button></a>}<Button onClick={refresh} disabled={refreshing} className="gap-2"><RefreshCw className={refreshing?'h-4 w-4 animate-spin':'h-4 w-4'}/>Refresh</Button></div></div></CardContent></Card>
  <section><div className="mb-3 flex items-end justify-between"><div><p className="text-xs font-semibold uppercase tracking-wider text-muted-foreground">01 · Snapshot</p><h2 className="mt-1 text-xl font-semibold">{integration.name} at a glance</h2></div><Badge variant="outline">{metrics.length} real signals</Badge></div>{metrics.length?<div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{metrics.map(m=>{const d=snapshotDelta(snapshots,profile.id,m.key);return <Card key={m.key} className="transition hover:-translate-y-0.5 hover:shadow-md"><CardContent className="p-5"><p className="text-xs text-muted-foreground">{m.label}</p><p className="mt-2 text-3xl font-bold tracking-tight">{formatNumber(m.value)}</p>{d&&<p className={`mt-1 text-[11px] font-medium ${d.delta>=0?'text-emerald-500':'text-rose-500'}`}>{d.delta>=0?'+':''}{formatNumber(d.delta)} since first snapshot</p>}</CardContent></Card>})}</div>:<Card className="border-dashed"><CardContent className="p-8 text-center"><Activity className="mx-auto h-8 w-8 text-muted-foreground/40"/><p className="mt-3 font-medium">No platform metrics were returned.</p></CardContent></Card>}</section>
  {profile.platform==='github'&&<section className="grid gap-5 lg:grid-cols-[1.5fr_1fr]"><Card><CardContent className="p-5 sm:p-6"><div className="flex items-center justify-between"><div><p className="text-xs font-semibold uppercase tracking-wider text-muted-foreground">02 · GitHub activity</p><h2 className="mt-1 font-semibold">Contribution activity</h2></div><Badge variant="outline">{activity.reduce((s,p)=>s+p.count,0).toLocaleString()} events</Badge></div><div className="mt-5 h-72">{activity.length>1?<ResponsiveContainer width="100%" height="100%"><AreaChart data={activity}><defs><linearGradient id="githubActivity" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor={tone.chart} stopOpacity={.35}/><stop offset="100%" stopColor={tone.chart} stopOpacity={0}/></linearGradient></defs><CartesianGrid strokeDasharray="3 3" stroke="hsl(var(--border))" vertical={false}/><XAxis dataKey="date" tick={{fontSize:10}} tickFormatter={v=>String(v).slice(5)}/><YAxis allowDecimals={false} tick={{fontSize:10}}/><Tooltip contentStyle={tooltip}/><Area type="monotone" dataKey="count" name="GitHub events" stroke={tone.chart} fill="url(#githubActivity)" strokeWidth={2.5}/></AreaChart></ResponsiveContainer>:<div className="flex h-full items-center justify-center rounded-xl border border-dashed text-sm text-muted-foreground">GitHub did not return dated public events.</div>}</div><p className="mt-3 text-[11px] text-muted-foreground">This is GitHub's returned event stream, not an invented contribution count.</p></CardContent></Card><Card><CardContent className="p-5 sm:p-6"><p className="text-xs font-semibold uppercase tracking-wider text-muted-foreground">Developer signals</p><div className="mt-4 space-y-3">{(profile.data?.breakdowns??[]).map(b=><div key={b.key} className="rounded-xl border p-3"><p className="text-xs font-semibold">{b.label}</p>{b.items.slice(0,6).map(i=><div key={i.label} className="mt-2 flex justify-between gap-3 text-xs"><span className="truncate text-muted-foreground">{i.label}</span><span className="font-semibold">{formatNumber(i.value)}</span></div>)}</div>)}</div></CardContent></Card></section>}
  {history.length>0&&<section><div className="mb-3"><p className="text-xs font-semibold uppercase tracking-wider text-muted-foreground">03 · Progress</p><h2 className="mt-1 text-xl font-semibold">Real snapshot history</h2></div><div className="grid gap-5 lg:grid-cols-2">{history.slice(0,4).map(s=><Card key={s.key}><CardContent className="p-5"><p className="font-semibold">{s.label}</p><div className="mt-4 h-52"><ResponsiveContainer width="100%" height="100%"><LineChart data={s.points}><CartesianGrid strokeDasharray="3 3" stroke="hsl(var(--border))" vertical={false}/><XAxis dataKey="date" tick={{fontSize:10}}/><YAxis tick={{fontSize:10}} domain={['auto','auto']}/><Tooltip contentStyle={tooltip}/><Line type="monotone" dataKey="value" stroke={tone.chart} strokeWidth={2.5} dot={false}/></LineChart></ResponsiveContainer></div></CardContent></Card>)}</div></section>}
  {(profile.data?.breakdowns??[]).length>0&&profile.platform!=='github'&&<section><div className="mb-3"><p className="text-xs font-semibold uppercase tracking-wider text-muted-foreground">04 · Breakdown</p><h2 className="mt-1 text-xl font-semibold">Signals that explain the profile</h2></div><div className="grid gap-5 lg:grid-cols-2">{(profile.data?.breakdowns??[]).map(b=><Card key={b.key}><CardContent className="p-5"><p className="font-semibold">{b.label}</p><div className="mt-4 h-64"><ResponsiveContainer width="100%" height="100%"><BarChart data={b.items.slice(0,10)} layout="vertical" margin={{left:10,right:10}}><CartesianGrid strokeDasharray="3 3" stroke="hsl(var(--border))" horizontal={false}/><XAxis type="number" tick={{fontSize:10}}/><YAxis type="category" dataKey="label" width={110} tick={{fontSize:10}}/><Tooltip contentStyle={tooltip}/><Bar dataKey="value" radius={[0,5,5,0]}>{b.items.slice(0,10).map((i,n)=><Cell key={i.label} fill={n===0?tone.chart:'hsl(var(--primary))'} fillOpacity={Math.max(.35,1-n*.06)}/>)}</Bar></BarChart></ResponsiveContainer></div></CardContent></Card>)}</div></section>}
  {profile.platform==='github'&&repos.length>0&&<section><div className="mb-3"><p className="text-xs font-semibold uppercase tracking-wider text-muted-foreground">05 · Projects</p><h2 className="mt-1 text-xl font-semibold">Repositories</h2></div><div className="grid gap-3 md:grid-cols-2 lg:grid-cols-3">{repos.slice(0,9).map(r=><a key={r.id??r.name} href={r.html_url??r.url} target="_blank" rel="noreferrer noopener"><Card className="h-full transition hover:-translate-y-0.5 hover:border-primary/30 hover:shadow-md"><CardContent className="p-4"><div className="flex items-center justify-between gap-2"><div className="flex min-w-0 items-center gap-2"><GitBranch className="h-4 w-4 shrink-0 text-muted-foreground"/><p className="truncate text-sm font-semibold">{r.name}</p></div>{r.private?<Lock className="h-3.5 w-3.5 text-amber-500"/>:<Globe2 className="h-3.5 w-3.5 text-emerald-500"/>}</div><p className="mt-2 line-clamp-2 min-h-10 text-xs leading-5 text-muted-foreground">{r.description||'No repository description.'}</p><div className="mt-4 flex flex-wrap gap-3 text-[11px] text-muted-foreground"><span className="inline-flex items-center gap-1"><Star className="h-3 w-3"/>{formatNumber(Number(r.stargazers_count??r.stars??0))}</span><span className="inline-flex items-center gap-1"><GitPullRequest className="h-3 w-3"/>{formatNumber(Number(r.forks_count??r.forks??0))}</span><span>{r.language||'Mixed'}</span></div></CardContent></Card></a>)}</div></section>}
 </div></div>;
}
