import { supabase } from '@/integrations/supabase/client';
import type { IntegrationId, IntegrationStatus } from './types';
const configuredApiUrl = import.meta.env.VITE_API_URL?.trim(); const API_BASE = (configuredApiUrl || '').replace(/\/+$/, '');
type SyncProfile = { id?: string; platform: string; handle: string; displayName?: string | null; avatarUrl?: string | null; profileUrl?: string | null; lastSyncedAt?: string; last_synced_at?: string };
type GitHubPrivateSync = { syncedAt: string; username: string; privateAccess: boolean; accessibleRepoCount: number; privateRepoCount: number };
export type OwnershipChallenge = { code: string; platform: 'leetcode' | 'codewars'; handle: string; expiresAt: string; instructions: string; verificationMode?: 'profile_summary' | 'webhook'; webhookUrl?: string; challengeId?: string };
async function backendRequest<T>(path: string, options?: RequestInit): Promise<T> { if (!API_BASE) throw new Error('The optional APIVue Node backend is not configured.'); const { data: { session } } = await supabase.auth.getSession(); const headers: Record<string, string> = { 'Content-Type': 'application/json', ...((options?.headers as Record<string, string> | undefined) ?? {}) }; if (session?.access_token) headers.Authorization = `Bearer ${session.access_token}`; const response = await fetch(`${API_BASE}${path}`, { ...options, credentials: 'include', headers }); if (!response.ok) { let message = `Request failed with status ${response.status}.`; try { const body = await response.json() as { error?: string; message?: string }; message = body.error ?? body.message ?? message; } catch {} throw new Error(message); } return response.status === 204 ? undefined as T : await response.json() as T; }
async function syncPublicProfile(platform: IntegrationId, handle: string): Promise<SyncProfile> { const clean = handle.trim().replace(/^@/, ''); if (!clean) throw new Error('A username or platform handle is required.'); const { data, error } = await supabase.functions.invoke('sync-profile', { body: { platform, handle: clean, save: true } }); if (error) { let message = error.message; const context = (error as { context?: { json?: () => Promise<unknown> } }).context; if (context?.json) { try { const body = await context.json() as { error?: string }; if (body?.error) message = body.error; } catch {} } throw new Error(message); } const payload = data as { error?: string; profile?: SyncProfile }; if (payload.error) throw new Error(payload.error); if (!payload.profile) throw new Error('The provider returned no profile data.'); return payload.profile; }
async function syncStackOverflowProfile(handle: string): Promise<SyncProfile> { const clean = handle.trim().replace(/^@/, ''); if (!clean) throw new Error('A Stack Overflow user ID or profile URL is required.'); const { data, error } = await supabase.functions.invoke('sync-stackoverflow', { body: { handle: clean } }); if (error) { let message = error.message; const context = (error as { context?: { json?: () => Promise<unknown> } }).context; if (context?.json) { try { const body = await context.json() as { error?: string }; if (body?.error) message = body.error; } catch {} } throw new Error(message); } const payload = data as { error?: string; profile?: SyncProfile }; if (payload.error) throw new Error(payload.error); if (!payload.profile) throw new Error('Stack Overflow sync returned no profile data.'); return payload.profile; }
export async function connectPublicProfile(platform: 'leetcode' | 'codewars' | 'stackoverflow' | 'tryhackme' | 'hackthebox', handle: string): Promise<SyncProfile> { const clean = handle.trim().replace(/^@/, ''); if (!clean) throw new Error('A username, user ID, or public profile URL is required.'); if (platform === 'stackoverflow') return syncStackOverflowProfile(clean); const provider = platform === 'leetcode' ? 'LeetCode' : platform === 'codewars' ? 'Codewars' : platform === 'tryhackme' ? 'TryHackMe' : 'Hack The Box'; const confirmed = window.confirm(`Track this public ${provider} profile?\n\n${clean}\n\nAPIVue will only use data exposed by the platform's public profile surface. No password, session cookie, or private token is requested.`); if (!confirmed) throw new Error('Profile addition cancelled.'); return syncPublicProfile(platform, clean); }
async function invokeOAuth(functionName: string, provider: string, body: Record<string, unknown> = {}): Promise<void> { const { data, error } = await supabase.functions.invoke(functionName, { body }); if (error) throw new Error(error.message); const payload = data as { error?: string; url?: string }; if (payload.error) throw new Error(payload.error); if (!payload.url) throw new Error(`${provider} authorization URL was not returned.`); window.location.assign(payload.url); }
async function startOwnershipVerification(platform: 'leetcode' | 'codewars', handle: string): Promise<OwnershipChallenge> { const clean = handle.trim().replace(/^@/, ''); if (!clean) throw new Error('A username is required.'); const { data, error } = await supabase.functions.invoke('start-profile-verification', { body: { platform, handle: clean } }); if (error) throw new Error(error.message); const result = data as { error?: string; challengeId?: string } & Partial<OwnershipChallenge>; if (result.error) throw new Error(result.error); if (!result.code || !result.expiresAt || !result.instructions) throw new Error('The verification challenge was incomplete.'); const challenge = { ...result, challengeId: result.challengeId } as OwnershipChallenge; sessionStorage.setItem('apivue.ownership.challenge', JSON.stringify(challenge)); return challenge; }
export async function beginOwnershipVerification(platform: 'leetcode' | 'codewars', handle: string): Promise<void> { await startOwnershipVerification(platform, handle); window.location.assign(`${import.meta.env.BASE_URL}dashboard/integrations/verify/${platform}`); }
export function getOwnershipChallenge(): OwnershipChallenge | null { try { const raw = sessionStorage.getItem('apivue.ownership.challenge'); return raw ? JSON.parse(raw) as OwnershipChallenge : null; } catch { return null; } }
export function clearOwnershipChallenge(): void { sessionStorage.removeItem('apivue.ownership.challenge'); }
export async function verifyOwnership(platform: 'leetcode' | 'codewars', handle: string, code: string): Promise<void> { if (platform === 'codewars') { const challenge = getOwnershipChallenge(); if (!challenge?.challengeId) throw new Error('The Codewars verification challenge is missing. Start verification again.'); const { data, error } = await supabase.functions.invoke('check-profile-ownership', { body: { platform, handle, challengeId: challenge.challengeId } }); if (error) throw new Error(error.message); const result = data as { error?: string; verified?: boolean; expired?: boolean }; if (result.error) throw new Error(result.error); if (result.expired) throw new Error('The Codewars verification challenge expired. Generate a new one.'); if (!result.verified) throw new Error('Codewars has not confirmed the webhook yet. Save the webhook in Codewars and try again.'); clearOwnershipChallenge(); return; } const { data, error } = await supabase.functions.invoke('verify-profile-ownership', { body: { platform, handle, code } }); if (error) throw new Error(error.message); const result = data as { error?: string; verified?: boolean }; if (result.error) throw new Error(result.error); if (!result.verified) throw new Error('Ownership verification did not complete.'); clearOwnershipChallenge(); }
export async function getIntegrationStatus(): Promise<IntegrationStatus> { if (API_BASE) { try { return await backendRequest<IntegrationStatus>('/api/integrations'); } catch {} } const { data, error } = await supabase.from('tracked_profiles').select('platform,handle,display_name,avatar_url,profile_url,last_synced_at,data').order('last_synced_at', { ascending: false }); if (error) throw new Error(error.message); const status: IntegrationStatus = { github: { connected: false }, codeforces: { connected: false }, leetcode: { connected: false }, codewars: { connected: false }, stackoverflow: { connected: false }, tryhackme: { connected: false }, hackthebox: { connected: false } }; for (const row of data ?? []) { const id = row.platform as IntegrationId; if (!(id in status) || status[id].connected) continue; const payload = row.data as Record<string, unknown> | null; status[id] = { connected: true, username: row.handle, handle: row.handle, displayName: row.display_name, avatarUrl: row.avatar_url, profileUrl: row.profile_url ?? undefined, lastSyncedAt: row.last_synced_at ?? undefined, privateAccess: payload?.privateAccess === true, accessibleRepoCount: typeof payload?.accessibleRepoCount === 'number' ? payload.accessibleRepoCount : undefined, ownershipVerified: payload?.ownershipVerified === true, verificationMethod: typeof payload?.verificationMethod === 'string' ? payload.verificationMethod : undefined }; } return status; }
export async function connectGitHub(): Promise<void> { await invokeOAuth('github-oauth-init', 'GitHub'); }
export async function connectCodeforces(_handle?: string): Promise<void> { await invokeOAuth('codeforces-oauth-init', 'Codeforces'); }
export async function connectStackOverflow(handle: string): Promise<void> { await connectPublicProfile('stackoverflow', handle); }
export async function disconnectGitHub(): Promise<void> { await disconnectPublicProfile('github'); }
export async function syncGitHub(): Promise<GitHubPrivateSync> { const { data, error } = await supabase.functions.invoke('sync-github-private', { body: {} }); if (error) throw new Error(error.message); const payload = data as Partial<GitHubPrivateSync> & { error?: string }; if (payload.error) throw new Error(payload.error); if (!payload.syncedAt || !payload.username) throw new Error('GitHub sync returned an incomplete result.'); return payload as GitHubPrivateSync; }
export async function syncIntegration(provider: Exclude<IntegrationId, 'github'>): Promise<{ syncedAt: string; handle: string; provider: string }> { const status = await getIntegrationStatus(); const handle = status[provider].username ?? status[provider].handle; if (!handle) throw new Error(`${provider} is not connected.`); const profile = provider === 'stackoverflow' ? await syncStackOverflowProfile(handle) : await syncPublicProfile(provider, handle); return { syncedAt: profile.lastSyncedAt ?? profile.last_synced_at ?? new Date().toISOString(), handle: profile.handle, provider }; }
export async function disconnectCodeforces(): Promise<void> { await disconnectPublicProfile('codeforces'); }
export async function connectLeetCode(handle: string): Promise<void> { await connectPublicProfile('leetcode', handle); }
export async function disconnectLeetCode(): Promise<void> { await disconnectPublicProfile('leetcode'); }
export async function connectCodewars(handle: string): Promise<void> { await connectPublicProfile('codewars', handle); }
export async function disconnectCodewars(): Promise<void> { await disconnectPublicProfile('codewars'); }
export async function disconnectStackOverflow(): Promise<void> { await disconnectPublicProfile('stackoverflow'); }
export async function disconnectTryHackMe(): Promise<void> { await disconnectPublicProfile('tryhackme'); }
export async function disconnectHackTheBox(): Promise<void> { await disconnectPublicProfile('hackthebox'); }
async function disconnectPublicProfile(provider: IntegrationId): Promise<void> { const { data, error } = await supabase.from('tracked_profiles').select('id').eq('platform', provider).limit(1); if (error) throw new Error(error.message); const id = data?.[0]?.id; if (!id) return; const { error: deleteError } = await supabase.from('tracked_profiles').delete().eq('id', id); if (deleteError) throw new Error(deleteError.message); }
